### ISSUE TITLE
when i use s3curl to operate the riak cs,i get error Access Denied

### ISSUE THREAD

**Issue by ghost** [basho/riak_cs#1000]
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/test</Resource><RequestId></RequestId></Error>

i am sure i use the right id and key.but i dont know why i meet this error?i hope you can help me. thank you .

**Comment by shino** [comment]
Please write down exact command you execute and its result.
Also please confirm you set `admin_key` and `admin_secret` in riak cs's `app.config`.
