### ISSUE TITLE
is there a performance test of riak cs? i use the riak cs [JIRA: RCS-178]

### ISSUE THREAD

**Issue by ghost** [basho/riak_cs#1002]

**Comment by ghost** [comment]
i am sorry there is a error happend in my explorer. so i  will write the detail question i want to ask.
  i want to use the riak cs as a cloud storge in cloud foundry. but when i deploy the riak cs and write some data to riak cs. i found that the read/write speed is very slow. compare to nfs server. i use the s3curl to put data to riak cs .i have the test as below:

  a 475M file write to riak cs need 1m53.915s
  a 296M file write to riak cs need 0m50.229s
is this the normal speed for riak cs? or maybe my operation error? i need to know more about the performance of riak cs . i hope you can help me .thank you.

**Comment by kuenishi** [comment]
I would like to mention that Riak creates 3 copies by default, even it's running in single node. Writing 3 copies at the same time will lead to random write where a hard disk is not so good at. Even if IO scheduler of kernel might optimize them, it won't be just 3x slower than direct write to normal file system like NFS. Please test at scale and tune up your installation by reading our documents [1] carefully.

[1] http://docs.basho.com/riak/latest/ops/tuning/linux/

**Comment by ghost** [comment]
wa, 3x slower than direct write to normal file system? and what about compare to other no-sql database? what about swift? is a System Performance Tuning very effective? riak creates 3 copies asynchronous or synchronization? can i config the number of copies? i know riak will keep the olddata until you  merge the data, but why riak keep 3 copies even in single node?
thank you,

**Comment by kuenishi** [comment]
For production system, minimum number of nodes is 5, to guarantee fault tolerance. And default n_val is 3. Nodes less than 5 cannot guarantee fault tolerance ... maybe lowering n_val to 2 or 1 might help avoiding 3 copes, and with fewer nodes, for micro benchmarking. But such micro benchmarking is often useless when what's being measured and how much it's the case for production environment.

Also, we don't do performance comparison against other databases and object storage like Swift. See [comparisons on Riak](http://docs.basho.com/riak/latest/theory/comparisons/) and [comparison against Swift](http://docs.basho.com/riakcs/latest/references/appendices/comparisons/Riak-Compared-to-Swift/) for further info.
