### ISSUE TITLE
riak-cs-control package not on packagecloud.io [JIRA: RCS-306]

### ISSUE THREAD

**Issue by markkimsal** [basho/riak_cs#1015]
The latest stable release of riak-cs-control package is still on the basho self hosted apt repository.  This requires managing 3 repos to get all the latest .deb packages instead of just 2 from package cloud.

It would be nice - if a new riak-cs-control release is not in the near future - to migrate the latest stable to packagecloud.io .

**Comment by kuenishi** [comment]
As we haven't been working much actively on riak-cs-control, copying current latest version to packagecloud.io would be a good idea.
Do you have any thought on this, @gcymbalski ?

**Comment by sebgie** [comment]
This would be great for configuration management! riak-cs-control is the only package that needs a special installation routine. It also looks like there is no build for Ubuntu 14.04 (http://docs.basho.com/riakcs/latest/riakcs-downloads/).

**Comment by shino** [comment]
riak-cs-control is not active for long time and it is not tested with latest version(s) of riak cs. Won't fix.

**Comment by gcymbalski** [comment]
Hey, I'm no longer with Basho, but am available for contract work if they should require assistance. Not putting personal time into Basho projects for a number of reasons. Thanks, folks.
