### ISSUE TITLE
Issue with riak-cs write performance [JIRA: RCS-320]

### ISSUE THREAD

**Issue by wingZero21** [basho/riak_cs#1017]
Hi,

We are seeing some issues with write performance currently when using riak-cs.

Are there any definitive steps/documentation to detail how to get good write performance as were seeing speeds of 2MB a second currently which we feel is quite slow.

When we do a DD on the file system were getting back 200MB so would like to be getting something similar to this rather than the 2MB that were seeing when using s3cmd or an s3 client.

Cheers

**Comment by TJC** [comment]
Riak is splitting your file up into many small (I think 1 MByte) chunks, and then making three copies of every chunk, distributed over your cluster. So you're never going to get close to the performance of "dd" doing a sequential write to your disks.

However I agree, it would be great if there was a guide to getting good performance, and also, some figures that other people have been able to achieve.

Stuff I've seen suggested around is:
- Changing i/o mode to NIF
- All the stuff in http://docs.basho.com/riak/latest/ops/tuning/linux/
- {put_concurrency, 4} (or higher)
- {put_buffer_factor, 8} (or higher)

**Comment by kuenishi** [comment]
There should be something wrong either in the config or in the software, as we haven't designed Riak CS such way. [I posted my thoughts on the mailing list](http://lists.basho.com/pipermail/riak-users_lists.basho.com/2015-January/016578.html) , please take a look at it.

I just want to be sure, does this share the same context with [the original thread](http://lists.basho.com/pipermail/riak-users_lists.basho.com/2014-November/016173.html) I responded to?

**Comment by shino** [comment]
Performance issue is hard to track / solve in gh issue interaction.

I will close this issue in the course of repo issue cleanup, but
please feel free to reopen if necessary or new updates.
