### ISSUE TITLE
Disable previous object after backpressure_sleep 

### ISSUE THREAD

**Issue by shino** [basho/riak_cs#1022]
From the comment https://github.com/basho/riak_cs/issues/1005#issuecomment-61354263

It seems that maybe_backpressure_sleep does harm.
It was added mainly for multipart upload because PUT Part
can be (massively) concurrent.

At normal (non-multipart) put, sleep after add_new_dict is bad idea.
Or (better?) we should set #state.riak_object/manifest to undefined
if we execute backpressure sleep in order not to use the previous result..

**Comment by kuenishi** [comment]
I think this is a good change to add spec to `riak_cs_manifest_fsm:get_and_update/4`.

**Comment by kuenishi** [comment]
All riak_test has passed. Will run sibling explosion test tomorrow.

**Comment by Basho-JIRA** [comment]
Testing to try and get it to appear on Sprint backlog - will close again shortly. 

**_[posted via JIRA by Deborah Rakow]**_

**Comment by Basho-JIRA** [comment]
Re-closing after adding to sprint 

**_[posted via JIRA by Deborah Rakow]**_
