### ISSUE TITLE
Setting ACL on objects using Transmit

### ISSUE THREAD

**Issue by iby** [basho/riak_cs#1024]
While the following works pretty well the same operation using transmit doesn't. I want to know what might be the reason for that?

``` shell
$ s3cmd setacl --acl-public s3://tst/1234.jpg
s3://tst/1234.jpg: ACL set to Public  [1 of 1]
```

![image](https://cloud.githubusercontent.com/assets/1086845/5159327/3545f572-7373-11e4-94ff-07a0ee7607d0.png)

**Comment by kellymclaughlin** [comment]
Is it the case that other operations with Transmit work as expected? Have you browsed our [docs page](http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-Transmit/) for configuring Transmit?

**Comment by iby** [comment]
Yes, I did and yes, browsing, creating buckets, uploading files, deleting objects and buckets, all works as expected. So far this was the only issue. Probably transmit sends a little abnormal command, but in theory it all should be working, right?

**Comment by kellymclaughlin** [comment]
In theory if other operations are successful it should work. Given that you are able to set the ACL with s3cmd, my guess is transmit is doing something odd, but that is just speculation. 

> Yes, I did and yes, browsing, creating buckets, uploading files, deleting objects and buckets, all works as expected. So far this was the only issue. Probably transmit sends a little abnormal command, but in theory it all should be working, right?
