### ISSUE TITLE
Install document links missing

### ISSUE THREAD

**Issue by shibukawa** [basho/riak_cs#1028]
http://docs.basho.com/riakcs/latest/cookbooks/installing/Installing-Riak-CS/#Installing-Riak-CS-on-a-Node

At almost middle of this long document, the links to platform specific documents of el6 and el7 are missing.
- Correct el6 document URL is https://packagecloud.io/basho/riak-cs/packages/el/6/riak-cs-1.5.2-1.el6.x86_64.rpm (.el6 part is gone now).
- It seems there is no packages for el7 on packagecloud. https://packagecloud.io/basho/riak-cs

**Comment by lucperkins** [comment]
I've fixed the el6 link and removed the el7 link for now (commit 6c4dd8f9454eb0cddd09cf46aff758285af764e2)
