### ISSUE TITLE
Document markup issue

### ISSUE THREAD

**Issue by shibukawa** [basho/riak_cs#1029]
http://docs.basho.com/riakcs/latest/cookbooks/Account-Management/#Retrieving-a-List-of-All-Users

`[s3-curl](http://aws.amazon.com/code/128)`

I think the above part should be link text to s3-curl, but markdown syntax is remained on the final document.

**Comment by shino** [comment]
@shibukawa Thank you very much for contribution!

I moved this issue to `basho_docs` repository because it's purely document related.
https://github.com/basho/basho_docs/issues/1456

Please feel free to open issues in this repository or `basho_docs`. Thanks again.
