### ISSUE TITLE
gh coordination test [JIRA: RCS-93]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak_cs#1045]
hey, hey!

**[Created in JIRA by Kota Uenishi]**

**Comment by kuenishi** [comment]
Cool.

**Comment by kuenishi** [comment]
Simulating merge-and-close

**Comment by Basho-JIRA** [comment]
Looks like it requires active closing. 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by Basho-JIRA** [comment]
Nicely done. 

**_[posted via JIRA by Kota Uenishi]**_
