### ISSUE TITLE
Calculate total amount of data to be collected at the storage calculation [JIRA: RCS-107]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak_cs#1054]
Bunch of users can't account for disk usage compared to the reported storage usage. To account for the amount of data deleted but not collected, improving the storage calculation by accounting manifests on writing, scheduled_delete, pending_delete and active data might help. Some confusion on multipart upload will be there, so naming might be different from original state diagram.

CC: http://lists.basho.com/pipermail/riak-users_lists.basho.com/2015-January/016579.html

**[Created in JIRA by Kota Uenishi]**

**Comment by shino** [comment]
To be added: Counts and total sizes per bucket for:
- non-MP writing state
- MP writing state
- pending_delete state
- scheduled_delete (can be divided into during leeway or older, useful?)

Items should be considered
- Total sized are guessed from Content-Length?
- MP writing does not have CL, sum of length of uploaded parts?
- MapReduce interface should be match between all riak nodes.
  Switch? Any automation possible?

**Comment by kuenishi** [comment]
For upgrade & version compatibility, I think updating `riak_kv.cs_version`might be good... although it supposed to be available after 2.1.0, setting it in advanced.config and utilizing might be enough for experimental feature. All map and reduce functions refer to that config and choose which to return, integer (undefined or something prior to 2.0.1) or some structured data ( >= 2.0.1). But the new reduce function can process both as input.

After operators finished upgrading all Riak and Riak CS, they can update all advanced config.

**Comment by kuenishi** [comment]
My idea of categorization:
- active objects + MP writing state (sum of data for accounting users) => for billing
- non-MP writing (estimate from content-size)
- MP writing, finished parts
- MP writing, not finished parts (estimate from content-size)
- pending_delete
- scheduled_delete within leeway
- scheduled_delete still not in leeway

BTW, how do we differentiate objects, who was deleted from active state (successfully uploaded and then deleted), or without being active (upload failed, and then deleted). If we know that difference, we can calculate more precisely.

**Comment by shino** [comment]
> I think updating riak_kv.cs_version might be good

The config is in riak. Map/reduce mod/fun are in riak-cs. I'm confused.

**Comment by kuenishi** [comment]
Those map and reduce functions are supposed to run in Riak. That's why using config in Riak. New map and reduce will be like this?

``` erlang
object_size_map(Object, _, Option) ->
   case {proplists:is_defined(use_legacy_stats, Option), (application:get_env(riak_kv, cs_version) >= 200001)} of
        {false, true} ->
             %% do new stat
             [SomeNewStructuredStats];
        _ ->
            %% do old stat calc...
           [{Mparts, MPBytes}]
    end.

object_size_reduce(Sizes, Option) ->
   case {proplists:is_defined(use_legacy_stats, Option), (application:get_env(riak_kv, cs_version) >= 200001} of
       {false, true} ->
             %% do new stat
            [lists:foldl(fun({MParts, MPBytes}, {Obj, Bytes}) -> fallback to old stats
                                    {Obj + MParts, Bytes, MPBytes};
                                (NewStructure, {Obj, Bytes}) ->
                                    {NewObj, NewBytes} = calc(NewStructure, Obj, Bytes);
                                ({MParts, MPBytes}, NewStructureAcc) ->
                                    {NewObj, NewBytes} = calc(NewStructureAcc, MParts, MPBytes);
                                (NewStructure, NewStructureAcc) ->
                                    merge(NewStructure, NewStructureAcc)
                            end, #some_new_structure{}, Sizes)];
        _ ->
            %% do old stat calc... maybe this clause isn't required
           {Objects,Bytes} = lists:unzip(Sizes),
           [{lists:sum(Objects),lists:sum(Bytes)}];
           [{Mparts, MPBytes}]
    end.
```

**Comment by shino** [comment]
Forgot one possibility. Stats for deleted bucket. Useful?

**Comment by kuenishi** [comment]
Cool > stats for deleted buckets

**Comment by shino** [comment]
What happens if final reducer runs with old CS MR module? I suspect it dies with undef or function_clause.

**Comment by kuenishi** [comment]
Ah... final reducer Riak node should be upgraded first?

**Comment by kuenishi** [comment]
Until that Riak CS should specify `use_legacy_stats` and `riak_kv.cs_version` shouldn't be configured.

**Comment by shino** [comment]
I don't know final reducer spawns on riak node that CS (of storage batch job) connects or randomly chosen.

**Comment by shino** [comment]
Agree > new config of Riak CS.
I'm thinking also option argument like `riak-cs-admin storage --detailed`.

**Comment by kuenishi** [comment]
I don't think that'd be nice, because the results are just stored again in Riak, not being displayed in console.

**Comment by shino** [comment]
> MP writing, not finished parts (estimate from content-size)

I guess there is neither content size nor anything to be basis for estimation before complete MP.

**Comment by Basho-JIRA** [comment]
Experimental feature.  Code is in 2.0.1 but hidden and undocumented  Will be part of 2.1.0 Pre-RC 

**_[posted via JIRA by Patricia Brewer]**_

**Comment by Basho-JIRA** [comment]
Release note: Add more storage usage metrics to be calculated in storage calculation. This is off by default, only can be turned `true` with `detailed_storage_calc` in `advanced.config` . With this option enabled, Operations can know how much manifests are `writing`, `pending_delete`, `scheduled_delete` and `active` which is not visible via API. Note that they do not always correctly reflect actual disk usage; `writing` may indicate more space than actually used, for example, an upload was cancelled in the middle but the calculation does not know how much actually storage space is consumed. In the same way `scheduled_delete` metric also could not be the exact amount of disk usage because blocks might partially be already deleted by garbage collection. 

**_[posted via JIRA by Kota Uenishi]**_
