### ISSUE TITLE
Compile and run (somehow) with OTP 17 [JIRA: RCS-109]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak_cs#1055]
null

**[Created in JIRA by Kota Uenishi]**

**Comment by Basho-JIRA** [comment]
- Update EQC to later version and use eqc_gen:utf8/0 for rewrite testing
- Update riak-erlang-client
- Update Cuttlefish, riak_cs_multibag
- Make xmerl dependency switchable 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by kuenishi** [comment]
Addressed by #1245 and https://github.com/basho/stanchion/pull/104

**Comment by shino** [comment]
self memo: OTP 18, build failed by the following error:

```
ERROR: compile failed while processing /home/shino/b/g/riak_cs-2.1/deps/riak_pb: {'EXIT',
    {{badmatch,
         {error,[],
             [{"src/riak_dt_pb.erl",
               [{243,erl_lint,{exported_var,'FNum',{'case',225}}}]}]}},
     [{protobuffs_compile,output,4,
          [{file,"src/protobuffs_compile.erl"},{line,147}]},
      {rebar_protobuffs_compiler,compile_each,2,
          [{file,"src/rebar_protobuffs_compiler.erl"},{line,120}]},
      {rebar_core,run_modules,4,[{file,"src/rebar_core.erl"},{line,446}]},
[snip]
```

**Comment by Basho-JIRA** [comment]
Release note line: Add Erlang/OTP 17 support 

**_[posted via JIRA by Kota Uenishi]**_
