### ISSUE TITLE
Incorrect return value for stop

### ISSUE THREAD

**Issue by DeadZen** [basho/riak_cs#1069]
https://github.com/basho/riak_cs/blob/develop/src/riak_cs_riak_client.erl#L165
_.-> stop without the ok..

**Comment by shino** [comment]
> _.-> stop without the ok..

Could you explain what does it mean?

If it is related with types of return value of `handle_call/3`,
it seems that `{stop, normal, ok, State}` is valid (am I wrong? :sweat_smile:  ):
http://www.erlang.org/doc/man/gen_server.html#Module:handle_call-3

```
[Result = {reply,Reply,NewState} | {reply,Reply,NewState,Timeout}
  | {reply,Reply,NewState,hibernate}
  | {noreply,NewState} | {noreply,NewState,Timeout}
  | {noreply,NewState,hibernate}
  | {stop,Reason,Reply,NewState} | {stop,Reason,NewState}]
```

**Comment by DeadZen** [comment]
Lol nope you're not wrong, seems it is valid on handle_call, suppose I was
too quick to reply, guess it means don't worry about it ;)

While we're on the subject, tho, why is the protocol buffer connection
terminated for every request with a preemptive cleanup?

**Comment by shino** [comment]
> why is the protocol buffer connection terminated for every request with a preemptive cleanup?

I guess its about `riak_cs_utils:close_riak_connection/1,2`. the functions do not stop PB processes, so  do not close TCP connection. The name is, oops, misleading :hear_no_evil: 
In riak cs node, PB processes, or TCP sockets, are pooled and maintained as long as they are valid/healthy.
