### ISSUE TITLE
Review comments on upgrade wiki page [JIRA: RCS-126]

### ISSUE THREAD

**Issue by shino** [basho/riak_cs#1070]
https://github.com/basho/riak_cs/wiki/Migrating-to-CS-2.0

General
- Write minimum riak version if needed (e.g. prefix_multi)

"Storage calculation"
- `add_paths` (´Д｀)ﾊｧ…
- multibag not needed for `add_paths`

"Riak CS 1.5 to 2.0, including Stanchion"
- Bad or no bad? > "because those configuration items are to preserve old and slow
  behaviours of Riak CS and have no bad effect on performance."
- For Stanchion, is there any preferable order (e.g. at first)
  to upgrade with riak and cs?
- In other words, will we test both stanchion1.5-riak2.0 and stanchion2.0-riak1.4?
- Connectivity matrix help?

```
  | connecter \ connectee | Riak 1.4  | Riak 2.0  | Stanchion 1.5 | Stanchion 2.0 |
  |-----------------------+-----------+-----------+---------------+---------------|
  | Stanchion 1.5         | OK        | probably? | N/A           | N/A           |
  | Stanchion 2.0         | probably? | OK        | N/A           | N/A           |
  | Riak CS 1.5           | OK        | probably? | OK            | OK?           |
  | Riak CS 2.0           | probably? | OK        | OK?           | OK            |
```

"Special Notes on Upgrading From Riak CS 1.4"
- Is it worthwhile to mention Difference of GC timestamp management?

"Riak CS nodes not corriding in a same box with live Riak node" section
- Do we support Riak CS 2.0 which connects to Riak 1.4?
- Do we support Riak CS 1.4/1.5 which connects to Riak 2.0?
- If either is false,
  - how to upgrade Riak CS that connects to Riak via L4 reverse proxy like HAProxy?
  - Currrent riak_test cases cover CS2.0-Riak2.0 or CS1.5-Riak1.4 combnations but
    do not do crossed ones.

**Comment by shino** [comment]
@kuenishi If you don't mind, I would suggest to move the wiki page to anywhere under git repository. It makes commenting review and tracking changes easier.

**Comment by kuenishi** [comment]
https://github.com/basho/basho_docs/pull/1529 Let's continue discussion there after I update the branch.

**Comment by shino** [comment]
Comments were moved to basho_docs's PR.

**Comment by kuenishi** [comment]
Let's go #1082.
