### ISSUE TITLE
+sfwi and +scl default value not correctly set in riak-cs.conf [JIRA: RCS-124]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak_cs#1071]
https://github.com/basho/riak_cs/pull/1068#issuecomment-74824765

**[Created in JIRA by Kota Uenishi]**

**Comment by Basho-JIRA** [comment]
(boom) https://github.com/basho/riak_cs/pull/1068#issuecomment-74824765 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by shino** [comment]
Behaivor at current develop (commit 4f13229efc964ce6e58ee7258fc1468109d49b0a)

Steps for confirmation
1. change riak-cs.conf
2. execute riak-cs chkconfig
3. grep scl or sfwi in the latest vm.*.args

## sfwi or `erlang.schedulers.force_wakeup_interval`
- default value (comment out in riak-cs.conf)
  
  `+sfwi 500`
- remove comment out (or comment in)
  
  `+sfwi 500`
- set custom value 12345
  
  `+sfwi 12345`

Works well! ヽ(￣▽￣)ノ

## scl or `erlang.schedulers.compaction_of_load`
- default value (comment out in riak-cs.conf)
  
  `+scl false`
- remove comment out (or comment in)
  
  `+scl false`
- set custom value true
  
  `+scl true`

Works well! ヽ(￣▽￣)ノ

**Comment by shino** [comment]
Oops, `erlang.schedulers.compaction_of_load` is for `scl`...
`erlang.schedulers.utilization_balancing` is for `sub` :cry: 

Above comment is updated. Both it seems that scl and sfwi works well :smile:

**Comment by shino** [comment]
Confirmed default values are `true` for `scl` and `500` for `sfwi` and they can be changed by setting custom values in `riak-cs.conf`.

Close.

**Comment by shino** [comment]
@kuenishi If there are any other concerns, please re-open and describe it :dizzy:
