### ISSUE TITLE
Cross-Origin Resource Sharing    about riak cs [JIRA: RCS-161]

### ISSUE THREAD

**Issue by xiaoliuliu2050** [basho/riak_cs#1077]
recently i am using riak and riak cs ,
and i happend to a problem ,
that is i want to upload a file directly to my database ,
but the brower has a problem ,you know it is Cross-Origin Resource Sharing,
i am here to ask help ,
how should i solve this problem ?

**Comment by zundra** [comment]
Agreed, I would also know how to solve this issue.

**Comment by kuenishi** [comment]
Dup with #581? It's just not supported yet 1.x and 2.0.
