### ISSUE TITLE
Riak CS should respond '400 Bad request' on multipart completion if the request has no part item. [JIRA: RCS-156]

### ISSUE THREAD

**Issue by ksauzz** [basho/riak_cs#1100]
API incompatibility issue which is found by [this test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L4476-L4486).

Although Amazon S3 respond 400 Bad request if multipart completion request has no part item, Riak CS accept the request.

A response sample from S3.

```
 HTTP/1.1 400 Bad Request
 x-amz-request-id: 7DCAB2138707FE68
 x-amz-id-2: hgAmdxlfDD7YxWsoktlpUx38KltSbSr4SXvjPi6wSQOPtAmnYMQYKYMuaLpvJ7Qn
 Content-Type: application/xml
 Date: Thu, 19 Mar 2015 16:23:46 GMT
 Connection: close
 Server: AmazonS3

<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>7DCAB2138707FE68</RequestId><HostId>hgAmdxlfDD7YxWsoktlpUx38KltSbSr4SXvjPi6wSQOPtAmnYMQYKYMuaLpvJ7Qn</HostId></Error>
```

**Comment by mrallen1** [comment]
For clarity's sake, this means the Content-Length is 0, correct?

**Comment by jadeallenx** [comment]
OK, so it looks like the test is supposed to do the following:
- Initiate a multipart upload
- Send 0 upload parts
- Send the "completed" upload message

Is my reading of this test case correct?

**Comment by kuenishi** [comment]
Yes, you're right, Mark.

**Comment by Basho-JIRA** [comment]
See https://github.com/basho/riak_cs/pull/1304 

**_[posted via JIRA by Mark Allen]**_
