### ISSUE TITLE
Misc bugs after ceph-tests update  [JIRA: RCS-159]

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#1103]
- [x] [Unnecessary NextMarker](https://github.com/basho/riak_cs/issues/1099)
- [x] CS should respond 'Not Found' if bucket is not existed. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L2381-L2394))
- [ ] Support non-canned ACL. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L3313-L3332)) 
- [ ] CS should respond 'InvalidAccessKeyId' if non-existent key id is sent. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L4203-L4213))
- [ ] CS should responds 'SignatureDoesNotMatch' if a signature is not match. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L4215-L4225))
- [x]  [Copy API should copy user meta data.](https://github.com/basho/riak_cs/issues/1097)
- [ ] [CS should refuse a empty request on multipart completion.](https://github.com/basho/riak_cs/issues/1100)
- [x] CS should respond NoSuchUpload. ([test](https://github.com/basho/s3-tests/blob/a38c056122ef2e8fbd5bc61b387463a16d228a59/s3tests/functional/test_s3.py#L4619-L4626))

(Copied from https://github.com/basho/riak_cs/pull/1096#issuecomment-84247404)

**Comment by shino** [comment]
Updated with the fixes by #1212

**Comment by kuenishi** [comment]
Fixed by #1212 ?
- Unnecessary NextMarker
- CS should respond 'Not Found' if bucket is not existed. (test)
- Copy API should copy user meta data.
- CS should respond NoSuchUpload. (test)

**Comment by shino** [comment]
Yes. I added checkboxes in the description and checked them.
