### ISSUE TITLE
Manual batch start causes last batch time to appear to be in the future [JIRA: RCS-200]

### ISSUE THREAD

**Issue by nerophon** [basho/riak_cs#1143]
https://github.com/basho/riak_cs/blob/develop/src/riak_cs_gc_d.erl#L538

Due to `next=Last` in the line above.

from DaJoe:

```
that issue is caused by the GC daemon using the 'next' entry in the record as the new 'last' when scheduling a new run
so if you manually start a batch, when it finishes, the last time is set to whenever the next regularly scheduled run would have been
fun is not exported, and only called in 3 places, I think the simplest fix would be to use batch_start instead of next
it is set to undefined immediately before the call
so either wait and set that to undefined here, or set next to batch_start before calling when it makes sense
in the case of the scheduled batch, batch_start and next happen to coincide
but in the case of a manual batch, they don't
schedule_next is called in 3 instances: init, batch completion, and batch cancellation
in the first last should be left undefined, the other two should use batch_start, and since batch_start defaults to undefined, you can use batch_start in all 3
```

**Comment by kuenishi** [comment]
I believe this should have been fixed by #1144, as the code structure had been totally changed - 'last' comes from only completed batch, regardless of either manual or periodical.

**Comment by shino** [comment]
Confirmed the bug at commit e0199af05e8e961a9c8288185f082c08acb34fd3, and fixed at commit 83009836fcacc42a81c0e0e834054b61c0864da1 as @kuenishi said.

The fix will be included in riak cs 2.1.

**Comment by Basho-JIRA** [comment]
This was unexpectedly fixed by RCS-199. 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by Basho-JIRA** [comment]
Release note: Fix manual batch start that causes last batch time to appear to be in the future 

**_[posted via JIRA by Kota Uenishi]**_
