### ISSUE TITLE
Integrity checking tool on buckets and users [JIRA: RCS-211]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak_cs#1161]
Motivated via issues like zd://11054

**[Created in JIRA by Kota Uenishi]**

**Comment by Basho-JIRA** [comment]
https://github.com/basho/internal_utilities/blob/master/basho-scripts/dvag_repair_scripts/bucket_audit.escript 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by kuenishi** [comment]
Addressed by #1202.

**Comment by Basho-JIRA** [comment]
For release note: a tool to check integrity between users and buckets added. For example, this could be used in case where a bucket is visible in listing buckets but not accessible, or a bucket is visible and exists but could not be deleted. 

**_[posted via JIRA by Kota Uenishi]**_
