### ISSUE TITLE
[Cross-link] Delete object fail with riakc_pb_socket [JIRA: RCS-251]

### ISSUE THREAD

**Issue by mbbroberg** [basho/riak_cs#1203]
See https://github.com/basho-labs/the-riak-community/issues/61. Community member @barcoyou didn't seem sure whether the error falls into this repo, so he posted to our community space. Please close this issue if it doesn't fall into this team's scope and suggest another portion of the stack.

**Comment by kuenishi** [comment]
This is not CS issue. Thanks for working on this.
