### ISSUE TITLE
Multipart upload with many parts triggers too big manifests and crash [JIRA: RCS-258]

### ISSUE THREAD

**Issue by NoKriK** [basho/riak_cs#1209]
Hello,

We have an issue with multipart uploads when uploading files with a lof of parts.
Uploading files with more than >1000 parts will create manifests way bigger than the recommended maximum size of 5MB seen here: https://github.com/basho/riak_cs/blob/develop/include/riak_cs.hrl#L482

We've seen that uploads with a lot of parts will trigger not only a warning in the logs but also slowdowns of the cluster which often finally result in OOM of Riak and crashs.

What's the recommended way to deal with that?
We've seen that a limitation on the maximum number of parts was introduced in https://github.com/basho/riak_cs/issues/945 but the limitation seems way too high (10K parts).

If it's impossible to deal with so many parts for RiakCS, shouldn't this be more restrictive?

Thanks,

**Comment by kuenishi** [comment]
Each part could be 5GB by maximum, I'd recommend expanding part size of your client app to some hundreds of megabytes to several gigs, to reduce the total number of parts. BTW what version of CS are you using? That warning also considers numbers of siblings - Riak CS 2.0 could have fewer number of siblings even if you have many concurrent uploads that possibly lead to sibling explosion.

**Comment by NoKriK** [comment]
We are doing tests on both RiakCS 1.5.4 and 2.0.1.
We do not control all clients, so we canot ensure they will be used with a small number of parts.

Shouldn't this setting be reduced by default to a value where the manifest won't get too large?
Another option is to make it configurable so that we can adjust the value to prevent crashes.

**Comment by kuenishi** [comment]
> Shouldn't this setting be reduced by default to a value where the manifest won't get too large?
> Another option is to make it configurable so that we can adjust the value to prevent crashes.

I think this would be a good idea to make `DEFAULT_MAX_PART_NUMBER` configurable at `riak_cs_wm_object_upload_part.erl` to limit the size of manifest, but may introduce an incompatibility with S3, which also has 10000.

**Comment by NoKriK** [comment]
This is not a real incompatibility, client Applications will still work.
The error is only triggered if the client application tries to send more parts than RiakCS can support.
For us, this is way better than seeing the cluster crash due to a multipart upload of 5k parts.

Too many parts are already not sustainable for the cluster, it seems better to throw a 400 than to see the cluster slowly die.

**Comment by shino** [comment]
Solutions at hand are:
1. Use riak 2.x with riak cs 2.x, and set `dvv_enabled` bucket property to `true`
2. To avoid OOM, set `max_siblings` to some value, like 50

The bloated manifest objects are triggered mainly by concurrency of uploading parts, but not by total part numbers primarily.

**Comment by shino** [comment]
I will close this issue in the course of repo issue cleanup, but please feel free to reopen if riak 2.x and DVV does not help.
