### ISSUE TITLE
Race conditions for gc status [JIRA: RCS-273]

### ISSUE THREAD

**Issue by shino** [basho/riak_cs#1229]
Two race conditions:
- State (idle or runnning) and detialed information
  - StateName is come from riak_cs_gc_manager (gen_fsm)
  - Detailed information is from riak_cs_gc_batch (gen_server)
  - it's possible that the command says "A garbage collection batch is
    in progress" but no detailed information
- riak_cs_gc_batch may be dead at riak_cs_gc_batch:current_state(Pid)

**Comment by Basho-JIRA** [comment]
No release note needed: new bug during development cycle. 

**_[posted via JIRA by Kota Uenishi]**_

**Comment by Basho-JIRA** [comment]
This was introduced at RCS-199 

**_[posted via JIRA by Kota Uenishi]**_
