### ISSUE TITLE
Remove admin_secret from riak-cs.conf and stanchion.conf [JIRA: RCS-307]

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#1274]

**Comment by shino** [comment]
Maybe, stanchion too.

**Comment by kuenishi** [comment]
Working branches:
- https://github.com/basho/riak_cs/compare/2.1...ku/remove-admin-secret
- https://github.com/basho/stanchion/compare/2.1...ku/remove-admin-secret

**Comment by kuenishi** [comment]
Pull requests (now running RT):
- https://github.com/basho/riak_cs/pull/1279
- https://github.com/basho/stanchion/pull/108

**Comment by shino** [comment]
Memo: doc change needed.

**Comment by kuenishi** [comment]
Change summary:

Riak CS and Stanchion both used `riak-cs.conf` or `stanchion.conf` to tell the system who was the administrator, with `admin.key` and `admin.secret`. Writing down `admin.secret` in non-encrypted form may risk the whole system of the secret being stolen. Administrator is able to (1) list all users, (2) disable/enable other users, (3) changing user accounts. Workaround for this is probably encrypting the partition that includes `/etc/riak-cs` directory.

These changes will enable Riak CS and Stanchion start up without `admin.secret` specified in configuration files, while `admin.key` is still needed. Even if `admin.secret` is written in those files, Riak CS and Stanchion ignores them. Initial procedure to create the very first account starting `anonymous_user_creation = true` does not change, though.

**Comment by shino** [comment]
Another related PR: https://github.com/basho/riak_cs_multibag/pull/33

**Comment by TJC** [comment]
hey guys -- could you update http://docs.basho.com/riak/cs/2.1.1/cookbooks/configuration/riak-cs/ to reflect the current correct and best practices in regard to the admin secret? I'm confused.

**Comment by ParthKolekar** [comment]
Plus one. Do we need to put the admin secrets in the file or not?
