### ISSUE TITLE
False 503 returned  [JIRA: RCS-314]

### ISSUE THREAD

**Issue by jenafermiller** [basho/riak_cs#1283]
**The impact of this bug is critical.**  The bug causes false `not found` errors that cause client downloads to fail with 503 errors, even though the data is in the cluster.  This bug also prevent read repair on the affected keys.  

Seen in [customer production environment](https://basho.zendesk.com/agent/tickets/12818), there is a bad clause in the following case statement in the [riak_cs_block_server.erl](https://github.com/basho/riak_cs/blob/2.0.1/src/riak_cs_block_server.erl#L278-L294) file:

```
    case get_block_local(RcPid, FullBucket, FullKey, GetOptions1, Timeout) of
        {ok, _} = Success ->
            ProceedFun(Success);
        {error, {insufficient_vnodes,_,need,_}} ->
            RetryFun(NumRetries + 2);
        {error, Why} when Why == notfound;
                          Why == timeout;
                          Why == disconnected;
                          Why == <<"{insufficient_vnodes,0,need,1}">>;
                          Why == {insufficient_vnodes,0,need,1} ->
            handle_local_notfound(RcPid, FullBucket, FullKey, GetOptions2,
                                  ProceedFun, RetryFun, NumRetries, UseProxyGet,
                                  ProxyActive, ClusterID);
        {error, Other} ->
            _ = lager:error("do_get_block: other error 1: ~p\n", [Other]),
            RetryFun(failure)
    end.
```

If the first member of the preflist is down, the error would be returned as `{insufficient_vnodes,0,need,1}` meaning it would never get to the `handle_local_notfound` call statement.  Instead, it would skip back up to the top and start over by repeating _only_ the n_val 1 request.  This effectively negates n_val for the entire preflist.  

This bug can be fixed in two ways.
1.  By removing the following two lines from the [riak_cs_block_server.erl](https://github.com/basho/riak_cs/blob/2.0.1/src/riak_cs_block_server.erl#L281-L282) file:

```
        {error, {insufficient_vnodes,_,need,_}} ->
            RetryFun(NumRetries + 2);
```
1.  By removing the `{sloppy_quorum, false}` option from the [riak_cs_block_server.erl](https://github.com/basho/riak_cs/blob/2.0.1/src/riak_cs_block_server.erl#L549) file:

```
    [{r, 1}, {n_val, 1}, {sloppy_quorum, false}].
```

**Comment by shino** [comment]
Thank you for reporting ;)

> This bug can be fixed in two ways.
> 1. By removing the following two lines from the riak_cs_block_server.erl file:
>     {error, {insufficient_vnodes,_,need,_}} ->

This branch seems like historical(?) one...  Current PB interface of riak
returns `Reason` part of `{error, Reason}` after turning it to binary
by `term_to_binary`. Then this branch is probably unnecessary, but some
code archeology and/or compatibility check with `riakc`/`riak_pb` is needed.

> By removing the {sloppy_quorum, false} option from the
>    riak_cs_block_server.erl file:

Assuming the first primary vnode is not alive, request of `n_val=1`
without `sloppy_quorum=false` will go into _fallback_ vnodes instead
of second primary vnode e. It will likely respond notfound.

> fail with 503 errors, even though the data is in the cluster.

GET Object processing in riak_cs is as follows:
- Get riak object for user (key is from Authorization header)
- Get riak object for CS/S3 bucket
- Get riak object for manifests
- If above get's are successful, respond 200 OK and send headers
- Get riak objects for object contents (called blocks)
  and stream them as HTTP response entity.

Block get failure causes errors at the last step, but already
responds HTTP status(200), so riak_cs just close socket.
At client side, it is observed as premature socket close
before reading full `Content-Length` bytes of response
entity.
