### ISSUE TITLE
using riak_kv instance outside riak-cs [JIRA: RCS-351]

### ISSUE THREAD

**Issue by vmalaga** [basho/riak_cs#1294]
Hi.

We are using riak-cs like S3 compatible storage and now we are planing to use riak kv to store keys-values.

Our question is whether to use the same instance of riak-kv used by riak-cs or if is more convenient to use a separate instance of riak-kv

**Comment by kuenishi** [comment]
Depending on what you want to do with that - technically it might be possible if you keep bucket namespaces separate from buckets used by CS, or using non-default bucket types. But be sure that your cluster has enough capacity to handle both workloads of KV and CS at once.
