### ISSUE TITLE
Update node_package in both CS and Stanchion [JIRA: RCS-357]

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#1297]
To include https://github.com/basho/node_package/pull/196. Once a new version tagged, I'll take it.

**Comment by Basho-JIRA** [comment]
The big merge to node_package was completed today but there's no new tag yet. So I will poke people first thing monday and get this hammered out Riak CS and stanchion. It's a very straightforward change once a tag has been committed. 

**_[posted via JIRA by Mark Allen]**_

**Comment by Basho-JIRA** [comment]
https://github.com/basho/riak_cs/pull/1306

https://github.com/basho/stanchion/pull/109

**_[posted via JIRA by Mark Allen]**_

**Comment by kuenishi** [comment]
CS and Stanchion were both updated to node_package 3.0.0. Good work, guys.
