### ISSUE TITLE
How to create a new user [JIRA: RCS-369]

### ISSUE THREAD

**Issue by ottuzzi** [basho/riak_cs#1319]
Hi,

   I cannot find a way to create a new user on riak-cs.
I followed the fast-track tutorial and everything is fine: riak-cs is working as expected, I created and admin user and I can upload/download files using s3cmd.
Now I spent the whole day trying to figure how to create a new user: what is the recommended way to create new users?
I tried https://github.com/basho/riak_cs_control.git but I cannot compile it :(
I tried Java API (https://github.com/basho-labs/riakcs-java-client) but when I tried to create a user I got http status 405.

Do you have any tip?
I searched through documentation but I cannot find a real how-to.

Thanks in advance
Bye
Piero

**Comment by angrycub** [comment]
Piero:

Apologies for the delay in answering your question.  [This article in the Riak-CS wiki](https://github.com/basho/riak_cs/wiki/Using-s3curl#create-user-without-anonymous_user_creation) provides examples for using s3curl to create a user once you have an admin user in the system and have anonymous_user_creation disabled. 

 I have created https://github.com/basho/basho_docs/issues/2204  to include this sample command in the Riak CS documentation.

Please let me know whether or not this resolves your issue.
