### ISSUE TITLE
Riak-CS fails to start on CentOS 6.8 (docker) [JIRA: RCS-381]

### ISSUE THREAD

**Issue by JMLX42** [basho/riak_cs#1329]
Hi,

I run riak-cs in a centos 6.8 docker container.
To make sure the data is persistent, I store the following directories in a separate data container:

- /var/data
- /var/log
- /var/lib/riak/
- /var/lib/riak-cs/
- /var/lib/stanchion/

When I restart my riak-cs container, I cannot restart riak-cs :

```
[root@aaf0e279323a /]# riak-cs console
config is OK
-config /var/lib/riak-cs/generated.configs/app.2017.01.18.09.38.29.config -args_file /var/lib/riak-cs/generated.configs/vm.2017.01.18.09.38.29.args -vm_args /var/lib/riak-cs/generated.configs/vm.2017.01.18.09.38.29.args
Exec:  /usr/lib64/riak-cs/erts-5.10.3/bin/erlexec -boot /usr/lib64/riak-cs/releases/2.1.0/riak-cs               -config /var/lib/riak-cs/generated.configs/app.2017.01.18.09.38.29.config -args_file /var/lib/riak-cs/generated.configs/vm.2017.01.18.09.38.29.args -vm_args /var/lib/riak-cs/generated.configs/vm.2017.01.18.09.38.29.args              -pa /usr/lib64/riak-cs/lib/basho-patches -- console
Root: /usr/lib64/riak-cs
Erlang R16B02_basho8 (erts-5.10.3) [source] [64-bit] [smp:4:4] [async-threads:64] [kernel-poll:true] [frame-pointer]


=INFO REPORT==== 18-Jan-2017::09:38:30 ===
    alarm_handler: {set,{system_memory_high_watermark,[]}}

=INFO REPORT==== 18-Jan-2017::09:38:30 ===
opening log file: "/var/log/riak-cs/access.log.2017_01_18_09"
Setup running ...
Directories verified. Res = {[ok],[]}
Setup finished processing hooks ...
Eshell V5.10.3  (abort with ^G)
(riak-cs@127.0.0.1)1> [os_mon] memory supervisor port (memsup): Erlang has closed

=INFO REPORT==== 18-Jan-2017::09:38:31 ===
    alarm_handler: {clear,system_memory_high_watermark}
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,riak_cs,{notfound,{riak_cs_app,start,[normal,[]]}}}"}

Crash dump was written to: /var/log/riak-cs/erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,riak_cs,{notfound,{riak_cs_app,start,[normal,[]]}}})
[root@aaf0e279323a /]# nano /var/log/riak-cs/erl_crash.dump
```
`/var/log/riak-cs/access.log.2017_01_18_09` is empty.
Here is what `/var/log/riak-cs/crash.log` says:

```
2017-01-18 09:38:31 =CRASH REPORT====
  crasher:
    initial call: application_master:init/4
    pid: <0.148.0>
    registered_name: []
    exception exit: {{notfound,{riak_cs_app,start,[normal,[]]}},[{application_master,init,4,[{file,"application_master.erl"},{line,133}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]}
    ancestors: [<0.147.0>]
    messages: [{'EXIT',<0.149.0>,normal}]
    links: [<0.147.0>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 27
    reductions: 119
  neighbours:
```

Removing and re-creating the data container solves the issue.
But I lose all my data so that's neither a fix nor a workaround.

Please tell me how we could solve this :)

**Comment by JMLX42** [comment]
Fix:

* do **NOT** mount `/var/lib/riak-cs` or `/var/lib/stanchion` from the data container
* make sure you call `/etc/init.d/riak-cs stop` before killing the container *or* run `riak-admin repair-2i` after restarting riak-cs in a container you killed without stoping riak-cs

**Comment by JMLX42** [comment]
Actually that does NOT fix the issue.

**Comment by kesslerm** [comment]
Please post your issue to the [riak-users][0] mailing list. Github issues are not intended for troubleshooting individual installations.

[0]: http://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com

**Comment by JMLX42** [comment]
After much trouble trying to fix this, the issue is actually much simpler.

The riak and riak-cs config files where stored in my app container, not in my persistent data container (where the riak data is). Whenever I upgraded the app container to a newly generated one, the conf files and especially the admin user credentials did not match.

IMHO the riak-cs error is completely misleading and useless : "notfound" should be "admin_user_not_found" or "invalid_admin_user". I will create a new issue for that if I get a positive feedback on the ML.
