### ISSUE TITLE
General question on project maturity and activity

### ISSUE THREAD

**Issue by ewstefan** [basho/riak_cs#1339]
Not really an issue: more a community question.

We've been exploring Riak-CS now for a couple of days and consider it as a potential inhouse-alternative to external S3-based storage providers.

Given the last commit was in January 2016, the question rose as to how well the project is supported and how mature the solution is. 

I'd be very thankful for any comments from the community on this.

**Comment by kuenishi** [comment]
I don't have answers for your questions, sorry, but [riak-users](https://lists.basho.com/mailman/listinfo/riak-users_lists.basho.com) is better place to ask questions. People are actively discussing things there.

**Comment by ewstefan** [comment]
Thanks for the pointer. I'm awaiting access cofirmation and will post there.

I keep this "issue" open till then in case someone else finds time to add a comment here.
