### ISSUE TITLE
Docs URL returns 403 error

### ISSUE THREAD

**Issue by chrismcfee** [basho/riak_cs#1342]
Hi, when trying to look at documentation for this project using the docs URL in the README, the documentation fails to load:

http://docs.basho.com/riakcs/latest/

403 Forbidden

Code: AllAccessDisabled
Message: All access to this object has been disabled
RequestId: 8F621679BF69AADA
HostId: V5A5bZwPEM93ScaXeZLuA80nhLFeHiCZqMfItQszQSTD8TzscTD2ZKAt/xglQu5VUh9IgAMNEuY=

http://docs.basho.com/riakcs/latest/tutorials/fast-track/

403 Forbidden

Code: AllAccessDisabled
Message: All access to this object has been disabled
RequestId: B95FAFCB7FBF6A43
HostId: JfSom8tedSwq5hl+1rsJGCWYW5hS1ETXo9ZKz9lD1YcRXm60qvnf5qjSf2hLIpR9UOXSYu/Db58=

http://docs.basho.com/riakcs/latest/references/apis/storage/

403 Forbidden

Code: AllAccessDisabled
Message: All access to this object has been disabled
RequestId: 7987B96ACF8EC0B2
HostId: XaGsXbJimEaYlO0iI8VzidzyuP/NvWRJTOlIepl/zWs0JUKB+tK1qN5fUrGKQzgey5FNeEBEhDs=

**Comment by lixen** [comment]
You can find the docs hosted here https://www.tiot.jp/riak-docs/ or go to the source https://github.com/basho/basho_docs

**Comment by chrismcfee** [comment]
Thank you!
