### ISSUE TITLE
ERROR: S3 error: 403 (AccessDenied): Access Denied on upload files

### ISSUE THREAD

**Issue by j4b3r** [basho/riak_cs#1349]
Hello

when try to upload files more than 15MB i see this error on s3cmd command:
 
 /usr/bin/s3cmd abortmp s3://test/100 -GQJNXtpQmC1Z5I11KkFBQ==
to abort the upload, or
  /usr/bin/s3cmd --upload-id -GQJNXtpQmC1Z5I11KkFBQ== put ...
to continue the upload.
ERROR: S3 error: 403 (AccessDenied): Access Denied

on riack-cs acces log i see this:

"PUT /buckets/test/objects/100/uploads/-GQJNXtpQmC1Z5I11KkFBQ==?partNumber=1 HTTP/1.1" 403 167 "" ""

**Comment by j4b3r** [comment]
Hello

i change  this line:
multipart_chunk_size_mb = 15
in my s3cfgfasttarck file and problem solved

**Comment by ghost** [comment]
@j4b3r - thanks for the follow-up explaining your fix - much appreciated.
