### ISSUE TITLE
500 server error when trying to create a key with a blank body.

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#143]
Use the following ruby script to reproduce: https://gist.github.com/db9006729bedd3b92ab7

**Comment by kellymclaughlin** [comment]
https://github.com/basho/riak_moss/pull/148

**Comment by slfritchie** [comment]
-1, sorry, both Reid and I seem to see 500 errors still, see comments in the PR for more details.

**Comment by slfritchie** [comment]
Bug testing script: https://gist.github.com/a4aceeef657dd6d1c5ee

**Comment by slfritchie** [comment]
+1 to merge, thanks!
