### ISSUE TITLE
Dialyzer warning review

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#144]

**Comment by slfritchie** [comment]
These patches depend on https://github.com/basho/riak-erlang-client/pull/42, which was
prepped by Sean and merged on 07 April 2012, yay.

(old: This PR is also necessary: https://github.com/basho/riak-erlang-client/pull/49 ... which was
closed in favor of PR 42 mentioned above)

**Comment by slfritchie** [comment]
https://github.com/basho/stanchion/pull/11

Update on 2012-04-10: this PR has been merged into the stanchion repo, many thanks to Bryan for review.

**Comment by slfritchie** [comment]
Ongoing work for the riak_moss repo is proceeding on this branch:

https://github.com/basho/riak_moss/compare/gh144-dialyzer-warning-review

**Comment by slfritchie** [comment]
https://github.com/basho/riak_moss/pull/166

**Comment by slfritchie** [comment]
Kelly, I updated https://gist.github.com/062a2468c33cfc4ba7da#comments with a comment.  I'm wondering if some out-of-date source in the deps dir are causing a cascade of type problems?

**Comment by slfritchie** [comment]
Merged, yay.

**Comment by slfritchie** [comment]
Didn't autoclose, oops.
