### ISSUE TITLE
Don't leak webmachine stacktraces on error

### ISSUE THREAD

**Issue by beerriot** [basho/riak_cs#157]
Since the default webmachine error handler is used, any time there is a Real Error, the user will see a webmachine/mochiweb generated response that is likely to include an Erlang stacktrace.  We probably don't want users seeing those, so we should write a Riak CS custom error handler.

Worse yet, there is a bug in the default error handler that means if we ever encounter an error while generating the stream for a get-object response, we will attempt to start generating that stream over afresh as the error message.  See https://github.com/basho/webmachine/issues/60

**Comment by kellymclaughlin** [comment]
Addressed by [this](https://github.com/basho/riak_cs/commit/9464353b4ece92bd21376206f584ac9bccd1789a) commit.
