### ISSUE TITLE
bad call to riak_moss_utils:get_user/2 in riak_moss_acl_utils:get_owner_data/1

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#164]
There's bad call in `riak_moss_acl_utils:get_owner_data/2` to the function `riak_moss_utils:get_user/2` is bogus.
Instead, I think it should be a call to `riak_moss_utils:get_user_by_index/3`, but that function requires a `RiakPid`,
and there isn't one easily available.

(Note: this error was found by Dialyzer)

**Comment by kellymclaughlin** [comment]
https://github.com/basho/riak_moss/pull/165
