### ISSUE TITLE
Add wrapper for "etop" 

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#167]
A while back, the "top" option was added to the `riak-admin` utility to make it easy for folks to use the OTP app "etop".  Such a thing is missing from the RCS packaging: there is no `riak-cs-admin` utility at the moment.  I'm not tremendously fussy about where it goes, but `riak-cs-admin top` would be consistent with the Riak product.

**Comment by kellymclaughlin** [comment]
Addressed [here](https://github.com/basho/node_package/pull/29)

**Comment by kellymclaughlin** [comment]
Changed merged to node_package master.
