### ISSUE TITLE
Mis-matched admin_key and admin_secret settings between Riak CS and Stanchion cause non-obvious failures [JIRA: RCS-347]

### ISSUE THREAD

**Issue by dreverri** [basho/riak_cs#169]
## Steps to reproduce
- Set differing admin credentials in the Riak CS and Stanchion `app.config` files

``` erlang
[
...
{riak_moss, [
    ...
    {admin_key, "key"},
    {admin_secret, "secret"},
    ...
]},
...
].
```

``` erlang
[
...
{stanchion, [
    ...
    {admin_key, "key1"},
    {admin_secret, "secret1"},
    ...
]},
...
].
```
- Restart Riak CS and Stanchion
- Attempt to create a new user

``` bash
$ curl http://localhost:8080/user --data email=dan@basho.com\&name=dan 
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/user</Resource><RequestId></RequestId></Error>
```
- Check the Riak CS and Stanchion logs for errors
## Expected

A log message in the Riak CS logs indicating that the new user request could not be completed because the admin credentials were not accepted by Stanchion.
## Actual

No obvious errors.

**Comment by shino** [comment]
Duplicated with #786
