### ISSUE TITLE
Use of r=1 in block_server causes file retrieval to fail when any Riak cluster node is down.

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#170]
The block_server fetches chunks using r=1. If any Riak node is down there is a high probability that the downed node houses a primary vnode for one of the file blocks. This leads to a scenario where the responding vnode may respond with {error, notfound} and this causes the file retrieval to fail. If the requesting client is s3cmd then this manifests as s3cmd hanging and chewing up cpu time.

**Comment by dreverri** [comment]
Reported in zd://1226

**Comment by reiddraper** [comment]
Based on my understanding of `notfound_ok` and `basic_quorum`, I suggest we change the block GET request
to also include `[{notfound_ok, false}, {basic_quorum, false}]`.
