### ISSUE TITLE
Riak CS deb package does not install on a default Ubuntu 10.04 LTS setup

### ISSUE THREAD

**Issue by dreverri** [basho/riak_cs#172]
## Steps to reproduce
- Download Riak CS deb package (`riak-cs_1.0.0-1_amd64.deb`)
- Attempt to install Riak CS

``` bash
$ sudo dpkg -i riak-cs_1.0.0-1_amd64.deb
Selecting previously deselected package riak-cs.
(Reading database ... 26683 files and directories currently installed.)
Unpacking riak-cs (from riak-cs_1.0.0-1_amd64.deb) ...
dpkg: dependency problems prevent configuration of riak-cs:
 riak-cs depends on libssl0.9.8 (>= 0.9.8m-1); however:
  Version of libssl0.9.8 on system is 0.9.8k-7ubuntu8.8.
dpkg: error processing riak-cs (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db ...
Processing triggers for ureadahead ...
Errors were encountered while processing:
 riak-cs
```
## Expected

Riak CS would install
## Actual

Riak CS doesn't install because of a dependency issue

**Comment by jaredmorrow** [comment]
@dreverri was this the riak-cs ubuntu package from the Lucid directory or Natty?   It is acting like the Natty package, so I want to be sure before I dig too deep.

**Comment by dreverri** [comment]
I did not realize there were separate packages; I will test the issue with the Lucid package now.

**Comment by dreverri** [comment]
You were correct. I was using the wrong package.
