### ISSUE TITLE
Store user key_secret fields as salted hashes

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#178]
Users' key_secret fields are currently stored as plaintext. They should be stored using a salted hash to increase security.

Changes for this should not be merged until [Issue 152](https://github.com/basho/riak_moss/issues/152) is completed and merged. Otherwise we are unable to help in the case that someone misplaces their key_secret.

**Comment by beerriot** [comment]
IANASecurityExpert, but I feel like I've seen quite a bit of "salted hashes aren't good enough; [use bcrypt, fool](http://yorickpeterse.com/articles/use-bcrypt-fool)" around the web lately.  Has my lack of expertise caused me to misunderstand the issue/advice, or should we be taking a different tack for stronger security?

**Comment by kellymclaughlin** [comment]
That's a good point to keep in mind, especially since there is an erlang wrapper for bcrypt available. It does seem that there is some confusion about the point of using salted hashes and not much consideration of the performance versus security assurance trade-offs in most of the blog posts on this subject (shocking I know), but given that storing a user's secret is a relatively infrequent event, the extra cost of calculation in our case may be acceptable. It's certainly worth considering.

**Comment by reiddraper** [comment]
The s3 admin console will tell you your secret key. They might be encrypting it on disk, but they present it in plaintext back to the user.

**Comment by kellymclaughlin** [comment]
Gonna close this. We may look at encrypting these on disk at some point, but will reopen a new issue for that.
