### ISSUE TITLE
KV backend and MapReduce src & BEAM file packaging

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#183]
Source management: the KV backend sources in the riak_moss repo causes eunit and dialyzer problems.  Those problems can be solved by: 1. moving them to the riak_kv repo, or 2. adding a rebar dependency riak_moss -> riak_kv and take the big chain of subsequent deps that that would create.

For the MapReduce BEAM files, do we need to create another dir, e.g. erl -pz, for BEAM files that aren't part of the Riak packaging but also is separate from the basho-patches dir?

**Comment by kuenishi** [comment]
This is solved via riak_cs_kv_multi_backend included in Riak CS and integrated tests on MapReduce testing with riak_test.

**Comment by kuenishi** [comment]
No, my mistake.
