### ISSUE TITLE
Provide ping resource for Riak CS health checks

### ISSUE THREAD

**Issue by dreverri** [basho/riak_cs#204]
This would be similar to the Riak ping resource available via the HTTP resource.

Additionally, it should return a non successful response if the Riak node it's communicating with is unresponsive. A Riak node may become unresponsive due to LevelDB issues (https://github.com/basho/eleveldb/issues/23).

Related issue:
https://help.basho.com/tickets/1381

**Comment by dreverri** [comment]
Related issue:
https://github.com/basho/riak_moss/issues/203

**Comment by kellymclaughlin** [comment]
I think this should use the `riakc_pb_socket:ping` function to check if the Riak node is responsive.

**Comment by kellymclaughlin** [comment]
https://github.com/basho/riak_moss/pull/207

**Comment by reiddraper** [comment]
+1'd the PR itself
