### ISSUE TITLE
Possible storage stats regression

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/riak_cs#210]
When using riak-cs-storage batch to generate storage usage samples, I'm now getting data back like so:

```
"Storage":{"Samples":[{"StartTime":"20120607T004100Z","EndTime":"20120607T004100Z"},{"StartTime":"20120606T195208Z","EndTime":"20120606T195208Z"}],
```

It appears these samples are missing the actual usage data.

**Comment by kuenishi** [comment]
Looks too old to reproduce (code changed so much), I'd like to close this unless good way to reproduce this.

**Comment by reiddraper** [comment]
Agree.
