### ISSUE TITLE
Usage queries via curl fail when auth_bypass = true

### ISSUE THREAD

**Issue by deanproctor** [basho/riak_cs#217]
When auth_bypass is enabled, querying usage reports via curl will fail with the below error:

$ curl http://localhost:8080/usage/ED8RGOBOL9PTHJR0J_BO?a
<?xml version="1.0" encoding="UTF-8"?><Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><Resource>/usage/ED8RGOBOL9PTHJR0J_BO</Resource><RequestId></RequestId></Error>

Disabling auth_bypass and querying a usage report on the same key returns data.

**Comment by kuenishi** [comment]
Should have been fixed via #854 which includes tests on `/usage`.

**Comment by kuenishi** [comment]
No, auth_bypass is a different thing.

**Comment by kuenishi** [comment]
After a survey again, `auth_bypass` is deprecated, and setting `admin_auth_enabled, false` in app.config will enable usage API without authorization header. In that case we have to be careful enough to set different admin IP and port from `cs_port` and `cs_ip` .
