### ISSUE TITLE
make rel should not specify skip_deps=true

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#255]

**Comment by reiddraper** [comment]
IIRC, it turns out we don't need `skip_deps=true`, the problem with eper not being included was addressed [here](https://github.com/basho/riak_moss/pull/249). Dizzy told me that skip_deps=true means skip making _releases_ for each dependency.

**Comment by kellymclaughlin** [comment]
Yep I tested that as well when reviewing that pr. Closing this issue.
