### ISSUE TITLE
test rolling upgrade of cs 1.2

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_cs#257]

**Comment by reiddraper** [comment]
Obstacles:
1. Riak and Riak CS need to be compiled with the same version of Erlang, because we use add_paths to share code from Riak CS in Riak (multi backend, map reduce code)
2. Riak CS 1.1 (is that what we're calling it?) upgrades and then serializes several Erlang records that previous versions of Riak CS won't understand.

**Comment by reiddraper** [comment]
I've done a simple test with compiling the current release of Riak CS and Stanchion (1.0.2 and 1.0.1 respectively) with Erlang R15B01, and using Riak 1.2 w/ Erlang R15B01, and I haven't yet run into any problems. Perhaps the first part of the upgrade could be:

(~~I do think this has a flaw w/ running list objects requests, but it's a brainstorm~~):

Before upgrading, here is the set up:

```
Riak 1.1.x R14B04
Riak CS 1.0.2 R14B04
Stanchion 1.0.1 R14B04
```

go through each node, and upgrade Riak, Riak CS and (if needed) Stanchion, and restart at the same time, to upgrade to (not Riak CS and Stanchion _just_ have Erlang versions changed):

```
Riak 1.2.0 R15B01
Riak CS 1.0.2 R15B01
Stanchion 1.0.1 R15B01
```

**Comment by reiddraper** [comment]
Do we need to do anything to upgrade user records? The user record in riak_moss.hrl has changed. This change too:

``` patch
 acl_from_meta([{?MD_ACL, Acl} | _]) ->                                                                             │                                                        
-    {ok, binary_to_term(list_to_binary(Acl))};                                                                     │                                                        
+    {ok, binary_to_term(Acl)}; 
```

**Comment by reiddraper** [comment]
It seems that the mixed R14 / R15 issue should be OK as long as each Riak node has references to .beam files compiled with the same version of Erlang. Modfun erlang map reduce requests should also be OK in these mixed clusters.

**Comment by reiddraper** [comment]
Cost-of-delay (ie. not doing work ;)) question, how bad would it be for us to _not_ do a rolling upgrade just for the Riak CS code, but have to restart all of those in the same window?

**Comment by reiddraper** [comment]
If it turns out we can't "just restart all rcs nodes at the same time", my first hunch is that we'll need to default to using the old user and manifest records (and behavior) again, with an app.config option to later flip. Since flipping that option won't be atomic (it would be just like restart all nodes at the same time), we'd need the nodes to default to the old behavior, but understand thew new user and manifest records, if they encounter them.

**Comment by kellymclaughlin** [comment]
I think a rolling upgrade may not be an option for us due to all the record upgrades. Perhaps at this point we think about what we can do to better support rolling upgrade next time. I'm thinking things like not barfing on unexpected versions of records, but I think the best we can do is return 503 so what are we gaining by trying to support a rolling upgrade? Maybe the best solution is bring up all the nodes with a slightly modified config and then swap the haproxy config and send it a SIGHUP, bring down the old nodes, reset the new node configs, then rolling restart each node and do a final haproxy restart.
