### ISSUE TITLE
Evaluate S3 compatibility using ceph/s3-tests 

### ISSUE THREAD

**Issue by dreverri** [basho/riak_cs#280]
https://github.com/ceph/s3-tests

**Comment by kuenishi** [comment]
I tried but the test hanged at 14th test. damn. Looks blocking at some PUT and waiting for response at recv.

**Comment by kuenishi** [comment]
https://gist.github.com/b59ee1d6d52c524bb3d5 < here's our result against master branch of ceph/s3-tests

**Comment by kellymclaughlin** [comment]
I've documented the setup for running the tests against Riak CS on OSX [here](https://github.com/basho/riak_cs/wiki/Running-Ceph-S3-Tests). Closing this issue since I don't think we need a long running issue open any longer.

**Comment by kuenishi** [comment]
:+1:
