### ISSUE TITLE
Riak CS should provide a graceful-stop command [JIRA: RCS-375]

### ISSUE THREAD

**Issue by dreverri** [basho/riak_cs#281]
A `graceful-stop` would behave as follows:
- Stop accepting new connections
- Return a 500 level error on the `ping` resource
- Finish any open requests
- Shutdown once all requests are complete

This command would allow system administrators to deploy rolling updates/upgrades without prematurely terminating any requests.

**Comment by reiddraper** [comment]
This should also (maybe optionally) store any in-memory access data into Riak.

**Comment by bsparrow435** [comment]
Fixed, closing.
