### ISSUE TITLE
riak-cs-storage status timeouts during storage calculation [JIRA: RCS-346]

### ISSUE THREAD

**Issue by ian-plosker** [basho/riak_cs#295]
As the storage calculation is performed synchronously in the riak_moss_storage_d fsm, when it is in the midst of calculating storage, it cannot report it's status.

**Comment by kuenishi** [comment]
duplicate with #286 .

**Comment by takabow** [comment]
This issue is not same as #286 . The same timeout problem was reported in the ZenDesk ticket https://basho.zendesk.com/tickets/10665

**Comment by shino** [comment]
Timeout error handling had been added at some release. Also, specific option of timeout for mapreduce is included. Close.
