### ISSUE TITLE
Compilation fails due to dependency mismatch

### ISSUE THREAD

**Issue by cmeiklejohn** [basho/riak_cs#297]
```
==> riak_test (get-deps)
ERROR: Dependency dir /Users/cmeiklejohn/Repositories/riak_cs/deps/lager failed application validation with reason:
{version_mismatch,{"/Users/cmeiklejohn/Repositories/riak_cs/deps/lager/src/lager.app.src",
                   {expected,"1.2.0"},
                   {has,"1.2.1"}}}.
ERROR: 'get-deps' failed while processing /Users/cmeiklejohn/Repositories/riak_cs/deps/riak_test: rebar_abort
```

Should we pin riak_cs to 1.2.0 or fix the riak_test dependency?

**Comment by cmeiklejohn** [comment]
Better question, why is riak_test a dependency of riak_cs?

**Comment by joedevivo** [comment]
The way riak_test is intended to be used is via rebar plugin. The riak_test dependency would have test scope is rebar handled something like that. As it stands, I was under the impression that the riak_test dependency was removed as part of the packaging process.
