### ISSUE TITLE
research supporting multipart upload

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_cs#300]
create a multipart upload plan

**Comment by slfritchie** [comment]
Reid's strawman:

https://gist.github.com/f700f4c5831ddeba588a

Scott's strawman:

https://gist.github.com/a3e588e4d524dbed2249

**Comment by slfritchie** [comment]
We've agreed to implement Reid's strawman, evolving as necessary to address shortcomings.

@reiddraper Feel free to use this card as you wish, I suppose, closing in favor of new ones or keeping it open.

**Comment by slfritchie** [comment]
The `gh300-multipart-upload` branch has now finished the first of three milestones.
1. DONE: all basic multipart upload functions with Erlang API is done
2. Add WebMachine wiring for HTTP API to step 1's functions
3. Modify to use appropriate strong consistency mechanisms

https://github.com/basho/riak_cs/tree/gh300-multipart-upload

**Comment by slfritchie** [comment]
Item 2, add WebMachine wiring, is now finished and ready for a first review:

https://github.com/basho/riak_cs/pull/369

**Comment by slfritchie** [comment]
PR #369 was closed via merge today, yay!
