### ISSUE TITLE
s3cmd rb --recursive fails on large bucket deletes

### ISSUE THREAD

**Issue by densone** [basho/riak_cs#301]
1) Create a bucket and put 3000 objects into it.  
2) run s3cmd rb s3://<yourbucket>/  

All files delete and you receive an error at the end of deletion: 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please report the following lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: AttributeError: 'NoneType' object has no attribute 'getchildren'
S3cmd:   1.0.0

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2006, in <module>
    main()
  File "/usr/bin/s3cmd", line 1950, in main
    cmd_func(args)
  File "/usr/bin/s3cmd", line 222, in cmd_bucket_delete
    _bucket_delete_one(uri)
  File "/usr/bin/s3cmd", line 210, in _bucket_delete_one
    return _bucket_delete_one(uri)
  File "/usr/bin/s3cmd", line 205, in _bucket_delete_one
    response = s3.bucket_delete(uri.bucket())
  File "/usr/share/s3cmd/S3/S3.py", line 238, in bucket_delete
    response = self.send_request(request)
  File "/usr/share/s3cmd/S3/S3.py", line 500, in send_request
    e = S3Error(response)
  File "/usr/share/s3cmd/S3/Exceptions.py", line 52, in __init__
    for child in error_node.getchildren():
AttributeError: 'NoneType' object has no attribute 'getchildren'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
    Please report the above lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

3) The bucket is never delete and is now inaccessible.  
4) You cannot delete said bucket. 

This error is reproducible 100% of the time on 37's cluster.  

If you test with a small bucket. Say 1 object in it. It works fine.  

5)  There are no errors in the riak log.  
6)  Errors from RiakCS  

2012-10-18 01:07:12.531 UTC [error] <0.6724.17> webmachine error: path="/seantest/"
{exit,{fatal,{{invalid_name,"<\"sean"},{file,file_name_unknown},{line,5},{col,30}}},[{xmerl_scan,fatal,2,[{file,"xmerl_scan.erl"},{line,4102}]},{xmerl_scan,scan_element,7,[{file,"xmerl_scan.erl"},{line,2048}]},{xmerl_scan,scan_content,11,[{file,"xmerl_scan.erl"},{line,2590}]},{xmerl_scan,scan_element,12,[{file,"xmerl_scan.erl"},{line,2128}]},{xmerl_scan,scan_content,11,[{file,"xmerl_scan.erl"},{line,2590}]},{xmerl_scan,scan_element,12,[{file,"xmerl_scan.erl"},{line,2128}]},{xmerl_scan,scan_content,11,[{file,"xmerl_scan.erl"},{line,2590}]},{xmerl_scan,scan_element,12,[{file,"xmerl_scan.erl"},{line,2128}]}]}

**Comment by densone** [comment]
Stanchion Log: 
2012-10-18 01:07:12.511 UTC [error] <0.21638.0> webmachine error: path="/buckets/seantest"
{exit,{timeout,{gen_server,call,[stanchion_server,{delete_bucket,<<"seantest">>,<<"ZAE4EJRFLJG5AYIOVLWH">>}]}},[{gen_server,call,2,[{file,"gen_server.erl"},{line,180}]},{stanchion_wm_bucket,delete_resource,2,[{file,"src/stanchion_wm_bucket.erl"},{line,110}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,169}]},{webmachine_resource,do,3,[{file,"src/webmachine_resource.erl"},{line,128}]},{webmachine_decision_core,resource_call,1,[{file,"src/webmachine_decision_core.erl"},{line,48}]},{webmachine_decision_core,decision,1,[{file,"src/webmachine_decision_core.erl"},{line,416}]},{webmachine_decision_core,handle_request,2,[{file,"src/webmachine_decision_core.erl"},{line,33}]},{webmachine_mochiweb,loop,1,[{file,"src/webmachine_mochiweb.erl"},{line,87}]}]}

root@riakcs-01:~#

**Comment by kuenishi** [comment]
I couldn't reproduce the problem with s3cmd 1.0.1 and Riak CS master. So I think you can avoid this problem by upgrading s3cmd. Because "s3:///" is invalid URL for s3cmd and S3 itself does not have such API that removes all buckets.
Maybe Riak CS had some error on processing a bucket named <<>> or <<"/">> - I'll try on it 

> $ ruby -e '(0..5000).each do |i| `echo "wow" > #{i}; s3cmd put #{i} s3://hoge; rm #{i}` end'
> $ s3cmd rb s3:///
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>     An unexpected error has occurred.
>   Please report the following lines to:
>    s3tools-bugs@lists.sourceforge.net
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> 
> Problem: ValueError: s3:///: not a recognized URI
> S3cmd:   1.0.1
> 
> Traceback (most recent call last):
>   File "/opt/local/bin/s3cmd", line 2006, in <module>
>     main()
>   File "/opt/local/bin/s3cmd", line 1950, in main
>     cmd_func(args)
>   File "/opt/local/bin/s3cmd", line 219, in cmd_bucket_delete
>     uri = S3Uri(arg)
>   File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/S3/S3Uri.py", line 35, in **new**
>     raise ValueError("%s: not a recognized URI" % string)
> ValueError: s3:///: not a recognized URI
> 
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
>     An unexpected error has occurred.
>     Please report the above lines to:
>    s3tools-bugs@lists.sourceforge.net
> !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
> $ s3cmd ls s3://hoge
> 2012-10-29 03:47         4   s3://hoge/0
> 2012-10-29 03:47         4   s3://hoge/1

**Comment by kuenishi** [comment]
OK, I've succeeded to reproduce on s3cmd 1.0.0, and any bucket access goes 403 after that.

**Comment by reiddraper** [comment]
See basho/stanchion#27 and basho/stanchion#28
