### ISSUE TITLE
Fix basho-patches dir paths

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#318]
The packaging for full support of the basho-patches directory appears to be broken for CS and perhaps for Stanchion.  Check latest packages and, if still broken, fix before the next release.

**Comment by kellymclaughlin** [comment]
This solution for this is [this](https://github.com/basho/node_package/pull/28) `node_package` fix. 

cc @jaredmorrow

**Comment by kellymclaughlin** [comment]
Change merged to node_package master.
