### ISSUE TITLE
list objects show all objects owned by the same user

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_cs#339]
Objects within a single bucket can have different 'owners', as distinguished in the `<Owner>` XML tag (with children `<ID>` and `<DisplayName>`). In Riak CS, we always return one owner for every object (I didn't investigate far enough to see if that user was the user who signed the request or the bucket owner). There's also an outstanding question about whether or not we're already storing the owner of the object in the manifest. @kellymclaughlin mentioned that we can use the owner from the object ACL, but I need to refresh my memory about ACLs, etc. to corroborate.

---

To see the desired behavior, here's what I did on (the real) s3.
1. Create a new bucket

``` shell
s3cmd -c ~/.s3cfg.real-s3-personal-account mb s3://object-owner-test
```
1. PUT an object

``` shell
s3cmd -c ~/.s3cfg.real-s3-personal-account put rebar s3://object-owner-test 
```
1. give another user `write` permission

``` shell
s3cmd -c ~/.s3cfg.real-s3-personal-account setacl --acl-grant=write:3e1cb52d83ecad448ecc254c2d38777066b035193363a0680866c30679c6ec41 s3://object-owner-test
```
1. have the other user PUT an object as well
2. list the keys

``` shell
s3curl --id personal http://object-owner-test.s3.amazonaws.com/ | xmllint --format
```

which yields:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
  <Name>object-owner-test</Name>
  <Prefix/>
  <Marker/>
  <MaxKeys>1000</MaxKeys>
  <IsTruncated>false</IsTruncated>
  <Contents>
    <Key>README.org</Key>
    <LastModified>2012-11-27T20:36:05.000Z</LastModified>
    <ETag>"abfa06d1ef4368f732d073a697c08c53"</ETag>
    <Size>1643</Size>
    <Owner>
      <ID>3e1cb52d83ecad448ecc254c2d38777066b035193363a0680866c30679c6ec41</ID>
      <DisplayName>jordanrw</DisplayName>
    </Owner>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
  <Contents>
    <Key>rebar</Key>
    <LastModified>2012-11-27T20:25:28.000Z</LastModified>
    <ETag>"055784217de7b9102e76bab97559668b"</ETag>
    <Size>114405</Size>
    <Owner>
      <ID>b0d16997c1f20ff5b6d4fe7b31558d9177b23d0c207a1dacd986e4f8ecab5363</ID>
      <DisplayName>reiddraper</DisplayName>
    </Owner>
    <StorageClass>STANDARD</StorageClass>
  </Contents>
</ListBucketResult>
```

note the differing `<Owner>` sections for the two objects.

**Comment by reiddraper** [comment]
Confirmed, we can just use the `owner` field from the ACL record, yay!

**Comment by kellymclaughlin** [comment]
This has been fixed right?

**Comment by reiddraper** [comment]
Yeah, verified working as expected on 36f61c7bd7f30202003fcc1e2bb22826cbf50879 (and likely much earlier).
