### ISSUE TITLE
make "Server" response header configurable at app.config

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#355]
"Server" response header is not configurable at current master, because following patch is not included the wed-content-length-with-streaming branch of webmachine defined at rebar.config

https://github.com/basho/webmachine/pull/51/files

And default server name should be like:

```
Server: Riak CS 1.2.2
```

Background:
Some customers use Riak CS as their storage service servers and may want to set the response header with their service name or brand.

**Comment by kuenishi** [comment]
Will be solved after #389 merged.

**Comment by shino** [comment]
@kuenishi  Ready to PR?

**Comment by kuenishi** [comment]
@shino rebased. ready for review.

**Comment by kuenishi** [comment]
PR is at #407

**Comment by kuenishi** [comment]
merged #407.
