### ISSUE TITLE
500 Error when listing bucket that does not exist

### ISSUE THREAD

**Issue by jrwest** [basho/riak_cs#385]
https://gist.github.com/46238d452af6f86c856a

this causes the `cs296_regression_test` & `cs347_regression_test` to fail with the most recent master - fe6761cce40ee3a68c031b66f8cb76b45abb89b6.

The culprit seems to be a bad match on this line because the return from `get_bucket_acl_policy` is `{error, notfound}`: https://github.com/basho/riak_cs/blob/master/src/riak_cs_wm_utils.erl#L417

**Comment by kuenishi** [comment]
now working on #393

**Comment by kuenishi** [comment]
#393 has been merged.
