### ISSUE TITLE
Update riak_repl test [JIRA: RCS-165]

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#408]
Also update erlcloud to error out when content length does not match returned content.

**Comment by bookshelfdave** [comment]
please see: https://github.com/basho/riak_cs/pull/516

**Comment by reiddraper** [comment]
Is this fixed by ee80c76167443cd0fb3a397f38a85e6eccc0cc4e?

**Comment by shino** [comment]
We have v3 test, including proxy_get. I guess this had been completed. (right?)

**Comment by kuenishi** [comment]
I think so...

**Comment by bookshelfdave** [comment]
yes!

**Comment by shino** [comment]
@kuenishi  @metadave Thanks :zap:
