### ISSUE TITLE
when trying creating a bucket already exists RiakCS returns 200

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#418]
... which is different from S3. I think this is corner-case-of-compatility, less important. Is this  intended or not? It this is a bug, it's easy to fix.

S3 returns:

```
ERROR: S3 error: 409 (BucketAlreadyOwnedByYou): Your previous request to create the named bucket succeeded and you already own it.
```

Returning 200 when bucket exists is idempotent and more RESTful than S3.

**Comment by kuenishi** [comment]
Let's love the inconsistency: I got 409 while Kelly got 200.

https://gist.github.com/kuenishi/4954399
https://gist.github.com/kellymclaughlin/4954373

**Comment by ksauzz** [comment]
i also got 200.

**Comment by kuenishi** [comment]
@ksauzz give me your gist.

**Comment by ksauzz** [comment]
https://gist.github.com/ksauzz/d6616ad4ae69b2c23ac7

**Comment by kuenishi** [comment]
Sometimes different, sometimes not different. I think returning 200 is good as REST behaviour, so closing this issue.
