### ISSUE TITLE
Add option to enforce multipart part sizes

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#420]
The AWS S3 spec says that the each multipart upload part, except for the last one, must be at least 5MBytes.  For testing purposes, I have not had any enforcement of that limit: if you want to upload 10 parts of 3 bytes each for a 30 byte file, you can do that.

A customer would like to see strict enforcement of this 5MB limit at completion time.  IMO we should add a configuration option so that we can use smaller parts for testing purposes.

Also, the same customer would like to see some kind of bad behavior/abuse checking prior to the "complete multipart upload" stage.  For example, if there are more than X multipart parts that are smaller than 5MB, then stop accepting new parts ... where X = 2 or 3 perhaps.

There is a small handful of legitimate uses for a few small multipart parts ... so we'd have to find some balance to avoid errors for Well-Behaved Clients.

**Comment by reiddraper** [comment]
+1 to all of this. I also find it really useful for testing to use small binaries, but for production we should enforce the 5MB limit.
