### ISSUE TITLE
Improve handling of siblings with user accounts

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#421]

**Comment by reiddraper** [comment]
Are we still planning on getting this in for 1.3?

**Comment by kellymclaughlin** [comment]
I was looking at this yesterday and I'm not really certain there is anything worth doing for 1.3. We already check for siblings when reading user data. The changes I'd like to see to this are more substantial and I don't think they could be ready or are really appropriate for 1.3. I was thinking of closing this and opening an issue to better describe what I think should be done for another release.

**Comment by reiddraper** [comment]
> I was thinking of closing this and opening an issue to better describe what I think should be done for another release.

+1

**Comment by kellymclaughlin** [comment]
I do not think there is anything to be done here for 1.3. Closing.
