### ISSUE TITLE
Use inet_parse:ipv4strict_address rather ipv4_address

### ISSUE THREAD

**Issue by shino** [basho/riak_cs#476]
Found in `riak_cs_s3_policy:parse_ip` .

```
4> inet_parse:ipv4_address("0").
{ok,{0,0,0,0}}
5> inet_parse:ipv4strict_address("0").
{error,einval}
```

**Comment by andrewjstone** [comment]
Hi @shino. The change is easy to make, but I'm not sure we want to make it.
It causes an existing test to fail, leading me to believe that behavior may be expected elsewhere. 
https://github.com/basho/riak_cs/blob/develop/test/riak_cs_s3_policy_test.erl#L40

The behavior would change from returning {{0,0,0,0}, {0,0,0,0}} to crashing with a badmatch.

Are you sure this is a change we want to make?

**Comment by shino** [comment]
@andrewjstone I can not determine whether the test case is appropriate or just a typo.

There are two choices, I think:
1. Try S3 policy behavior in brute-force way, and estimate its parsing logic and implement it.
2. Use strict.

@kota Do you know whether the IP range `192.3.1/16` in the test case is intentional or not?

**Comment by kota** [comment]
@shino You are mentioning wrong person.

**Comment by shino** [comment]
sorry for wong mention.

**Comment by shino** [comment]
@andrewjstone I tried S3 bucket policy with "wrong" IP format and S3
responded with 500 Internal Error. So Riak CS's parse logic should be
strict and the test case should be corrected.

command:

```
s3cmd -d setpolicy scripts.local/s3/s3_policy_ip_range_put.txt s3://shino.shun.test-ip-range
```

policy json (`aws:SourceIp` has "wrong" format)

```
{
  "Version": "2008-10-17",
  "Id": "Policy1359983382391",
  "Statement": [
    {
      "Sid": "Stmt1359983375917",
      "Action": [
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::shino.shun.test-ip-range/*",
      "Condition": {
         "IpAddress" : {
                    "aws:SourceIp": "192.168/24" 
                }
      },
      "Principal": {
        "AWS": [
          "*"
        ]
      }
    }
  ]
}
```

**Comment by andrewjstone** [comment]
@reiddraper @kellymclaughlin @slfritchie @shino 
Looking through [parse_ip/1](https://github.com/basho/riak_cs/blob/develop/src/riak_cs_s3_policy.erl#L797) , it purposefully allows bad addresses with the bit shifting. However, According to @shino, S3 does not allow them. I'm not sure if we should just completely disallow them. Trying to reach out to whoever wrote that code.

**Comment by shino** [comment]
cc: @kuenishi

**Comment by jj1bdx** [comment]
@andrewjstone Can you elaborate on what you intend to say about "purposefully" allowing bad addresses on https://github.com/basho/riak_cs/blob/develop/src/riak_cs_s3_policy.erl#L797 ? Any examples?

**Comment by andrewjstone** [comment]
@jj1bdx I meant that all that bit shifting code exists to allow invalid addresses. The test is there to ensure the bitshifting works. I will be removing that and making changes to the tests in order to use ipv4strict_address.

**Comment by kuenishi** [comment]
@andrewjstone Yes, it's misleading to users. I just obeyed general definition of IP address. And thanks, go ahead!

**Comment by kuenishi** [comment]
BTW, surprised about S3 returns 500.. looks like a bug. Usually it returns 400 in case of bad policy description, `Malformed Policy Something`.

**Comment by kuenishi** [comment]
I think in case of this error, returning `400 MalformedPolicy` is good. Adding a description in Body XML like S3 may be another issue.

**Comment by kellymclaughlin** [comment]
This looks to be resolved. Can we close this issue?

**Comment by andrewjstone** [comment]
Done.
