### ISSUE TITLE
Riak CS should better handle temporary disconnects from Riak

### ISSUE THREAD

**Issue by dreverri** [basho/riak_cs#502]
Currently, if RiakCS is disconnected from Riak any active requests that depend on Riak (e.g. uploads, downloads) fail. It would be ideal if RiakCS attempted to reconnect to Riak to avoid exposing temporary failures to clients.

The riak-erlang-client supports the options `auto_reconnect` and `queue_if_disconnected`, however, it doesn't appear to have any type of failure threshold which could be problematic.

**Comment by dreverri** [comment]
See also https://basho.zendesk.com/agent/#/tickets/3968

**Comment by reiddraper** [comment]
Closing in favor of #262
