### ISSUE TITLE
init script failure in stop() with multiple beam processes

### ISSUE THREAD

**Issue by fprimex** [basho/riak_cs#510]
"""
The stop() function in the /etc/init.d/stanchion, /etc/init.d/riak and /etc/init.d/riak-cs scripts checks for the RETVAL but pidof is using too general an argument. If there are multiple beam.smp processes running then the script will report a failure.

A better check might be to perform a pgrep with the argument of DAEMON.

```
RETVAL=`pgrep -f $DAEMON`
```

"""

Related:
https://basho.zendesk.com/agent/#/tickets/4127

**Comment by fprimex** [comment]
Note: pgrep is probably not portable across all of the supported CS platforms.

**Comment by jaredmorrow** [comment]
This and basho/stanchion#47 are the same issue, so linking here.

**Comment by mcnamarabrian** [comment]
It looks like the only supported OS that does not support pgrep is OS X.  Perhaps a case statement could be used to check the OS before determining the command to run.

Thanks!
Brian

**Comment by jaredmorrow** [comment]
I have a pretty simple solution to this problem actually using a new function I added called getpid, so we only shutdown or kill the right process.  I just have to find some time to get it pushed.

**Comment by jaredmorrow** [comment]
Fixed and will be available in 1.3.1 packages.
