### ISSUE TITLE
 Locations request using s3curl fails with 403

### ISSUE THREAD

**Issue by joecaswell** [basho/riak_cs#517]
when using s3curl, the request:
http_proxy=172.17.23.1:8080 s3curl.pl --id admin "http://west.s3.amazonaws.com?location" 
fails with the following exchange:

```
GET http://west.s3.amazonaws.com?location HTTP/1.1
User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
Host: west.s3.amazonaws.com
Accept: */*
Proxy-Connection: Keep-Alive
Date: Fri, 29 Mar 2013 22:50:52 +0000
Authorization: AWS VKH0GCMLGNH1GRBFBIGI:9ZxEmcU71Qdmz25NUJFJRtledcY=

HTTP/1.1 403 Forbidden
Server: Riak CS
Date: Fri, 29 Mar 2013 22:50:52 GMT
Content-Type: application/xml
Content-Length: 159

<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/west</Resource><RequestId></RequestId></Error>
```

A similar request using s3cmd succeeds:

```
GET http://west.s3.amazonaws.com/?location HTTP/1.1
Host: west.s3.amazonaws.com
Accept-Encoding: identity
content-length: 0
Authorization: AWS VKH0GCMLGNH1GRBFBIGI:KRNRs3rvO7R/V0phTtGxcukgDX4=
x-amz-date: Fri, 29 Mar 2013 22:50:55 +0000

HTTP/1.1 200 OK
Server: Riak CS
Date: Fri, 29 Mar 2013 22:50:55 GMT
Content-Type: application/xml
Content-Length: 69

<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
```

**Comment by shino** [comment]
There is one difference of the trailing slash after `west.s3.amazonaws.com`.
Does it matter?

**Comment by shino** [comment]
200/403 according to with/without trailing slash:

```
$ s3curl.pl --id local_rcs -- -w '\n%{http_code}\n' -s -x 127.0.0.1:8080 \
    'http://test.s3.amazonaws.com/?location'
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"/>
200

$ s3curl.pl --id local_rcs -- -w '\n%{http_code}\n' -s -x 127.0.0.1:8080 \
    'http://test.s3.amazonaws.com?location'
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access Denied</Message><Resource>/test</Resource><RequestId></RequestId></Error>
403
```

**Comment by shino** [comment]
One more memo: AWS S3 responds with 200 whether there is trailing slash or not.

Maybe related to URL rewrite, such as #515. If so there should be `with_trailing_slash` flag.

**Comment by kellymclaughlin** [comment]
The root of this issue is actually `erlang:decode_packet/3` as used [here](https://github.com/basho/mochiweb/blob/1.5/src/mochiweb_http.erl#L107). The following erlang console snippet illustrates the issue:

```
(riak-cs@127.0.0.1)1> Pkt1 = <<"GET http://test.s3.amazonaws.com?location HTTP/1.1\r\n">>.
(riak-cs@127.0.0.1)1> Pkt2 = <<"GET http://test.s3.amazonaws.com/?location HTTP/1.1\r\n">>.
(riak-cs@127.0.0.1)3> Decode1 = erlang:decode_packet(http, Pkt1, []).
{ok,{http_request,'GET',
                  {absoluteURI,http,"test.s3.amazonaws.com?location",
                               undefined,"/"},
                  {1,1}},
    <<>>}
(riak-cs@127.0.0.1)4> Decode2 = erlang:decode_packet(http, Pkt2, []).
{ok,{http_request,'GET',
                  {absoluteURI,http,"test.s3.amazonaws.com",undefined,
                               "/?location"},
                  {1,1}},
    <<>>}
```

These snippets from [rfc 1738](http://www.ietf.org/rfc/rfc1738.txt) lead me to believe that `erlang:decode_packet/3` is actually adhering to the spec as written:

> An HTTP URL takes the form:
> 
> ```
> http://<host>:<port>/<path>?<searchpart>
> ```

and

> The `<path>` is optional, as is the `<searchpart>` and its
> preceding "?". If neither `<path>` nor `<searchpart>` is present, the "/"
> may also be omitted.

I interpret this as saying that for the `/` to be omitted both `<path>` and `<searchpart>` must not be present; otherwise, the URL is malformed. I think this is just a case where we do need users or clients to adhere to the specification and just because S3 may choose to support such interaction does not mean we necessarily have to.

**Comment by shino** [comment]
Agree.

I did not consider specification and only tried CS/S3 behavior.

**Comment by kellymclaughlin** [comment]
Closing.

**Comment by ghost** [comment]
i get this error too,how to deal with it?

**Comment by shino** [comment]
@HelloLin Add trailing slash.

**Comment by ghost** [comment]
@shino where to add?i got the error:

/root/s3curl/s3curl.pl --id=admin --head http://p-riakcs.9.91.18.38.xip.io/cloudfoundry-packages/12/01/120186da-f434-4c73-b926-b4d68f33d63f
HTTP/1.1 200 OK
Connection: close
Content-Length: 2190
Content-Type: application/zip
Date: Tue, 16 Sep 2014 12:28:24 GMT
Etag: "3ee22f6fdd3311abe920cd3db23f8a46"
Last-Modified: Tue, 16 Sep 2014 01:37:08 GMT
Server: Riak CS

/root/s3curl/s3curl.pl --id=admin --head http://p-riakcs.9.91.18.38.xip.io/cloudfoundry-packages/12/01/120186da-f434-4c73-b926-b4d68f33d63f
HTTP/1.1 403 Forbidden
Connection: close
Content-Length: 277
Content-Type: application/xml
Date: Tue, 16 Sep 2014 12:28:30 GMT
Server: Riak CS

please help me thank you very much.

**Comment by shino** [comment]
@HelloLin  It seems different issue, but I can not tell anything from the information.
This "Github issues" is a bug tracker, so it is better to ask it in riak-users mailing lists. Thanks.
