### ISSUE TITLE
Unable to create first user

### ISSUE THREAD

**Issue by livid** [basho/riak_cs#529]
Followed every step in documentation, when I'm trying to create first user through curl:

curl -H 'Content-Type: application/json' -X POST -v --data '{"email":"admin@example.com", "name":"admin"}' http://127.0.0.1:8000/riak-cs/user

I got this:
- About to connect() to 127.0.0.1 port 8000 (#0)
-   Trying 127.0.0.1... connected
  > POST /riak-cs/user HTTP/1.1
  > User-Agent: curl/7.22.0 (x86_64-pc-linux-gnu) libcurl/7.22.0 OpenSSL/1.0.1 zlib/1.2.3.4 libidn/1.23 librtmp/2.3
  > Host: 127.0.0.1:8000
  > Accept: _/_
  > Content-Type: application/json
  > Content-Length: 45
  > 
- upload completely sent off: 45out of 45 bytes
  < HTTP/1.1 503 Service Unavailable
  < Vary: Accept
  < Server: Riak CS
  < Location: http://127.0.0.1:8000/riak-cs/user
  < Date: Wed, 10 Apr 2013 14:28:44 GMT
  < Content-Type: application/xml
  < Content-Length: 192
  < 
- Connection #0 to host 127.0.0.1 left intact
- Closing connection #0
  <?xml version="1.0" encoding="UTF-8"?><Error><Code>ServiceUnavailable</Code><Message>Please reduce your request rate.</Message><Resource>/riak-cs/user</Resource><RequestId></RequestId></Error>

**Comment by kellymclaughlin** [comment]
Have you specifically set the listener port to `8000`? The default is `8080`. Did you see `8000` referenced in some documentation?

**Comment by livid** [comment]
Yes that section is uncommented.

**Comment by kellymclaughlin** [comment]
Do you have either `anonymous_user_creation` set to `true` or `admin_auth_enabled` set to `false`? You must have one of these set to create the initial user. Also, the value of `admin_auth_enabled` must be set prior to starting the Riak CS node and that setting is only used when `admin_ip` and `admin_port` are uncommented.

**Comment by dmitriid** [comment]
I have the same issue.

```
$ curl -H 'Content-Type: application/json' -X POST http://localhost:80/riak-cs/user --data '{"email":"foobar@example.com", "name":"admin user"}' -v
* About to connect() to localhost port 80 (#0)
*   Trying ::1...
* Connection refused
*   Trying 127.0.0.1...
* connected
* Connected to localhost (127.0.0.1) port 80 (#0)
> POST /riak-cs/user HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8r zlib/1.2.5
> Host: localhost
> Accept: */*
> Content-Type: application/json
> Content-Length: 51
> 
* upload completely sent off: 51 out of 51 bytes
< HTTP/1.1 503 Service Unavailable
< Vary: Accept
< Server: Riak CS
< Location: http://localhost/riak-cs/user
< Date: Sat, 27 Apr 2013 09:31:37 GMT
< Content-Type: application/xml
< Content-Length: 192
< 
* Connection #0 to host localhost left intact
<?xml version="1.0" encoding="UTF-8"?><Error><Code>ServiceUnavailable</Code><Message>Please reduce your request rate.</Message><Resource>/riak-cs/user</Resource><RequestId></RequestId></Error>* Closing connection #0
```

Relevant sections from the config:

riak_cs

```
 {riak_cs, [
          %% == Basic Configuration ==

          %% Riak CS http/https port and IP address to listen at
          %% for object storage activity
          {cs_ip, "127.0.0.1"},
          {cs_port, 80 } ,

          %% Riak node to which Riak CS accesses
          {riak_ip, "127.0.0.1"},
          {riak_pb_port, 27007 } ,
          {anonymous_user_creation, true},
```

riak

```
 {riak_api, [
        {pb_ip,   "127.0.0.1" },
        {pb_port, 27007 }
        ]},
```

Same thing if I set a different admin_port and send a request to that. There's nothing in the logs

**Comment by hectcastro** [comment]
@livid @dmitriid Can you guys please send your Riak, Riak CS, and Stanchion `app.config` to hector@basho.com, and I'll try to reproduce your issue?

**Comment by dmitriid** [comment]
Key word: Stanchion!

After staring Stanchion everything worked :)

**Comment by hectcastro** [comment]
@livid Did you get it working by enabling Stanchion like the comment above?

**Comment by kandalf** [comment]
I'm having the same problem and not working even with Stanchion running.
I'm using the Debian 64 package running on a VirtualBox.

Could it be related to ulimit? I have set ulimit -n 4096 in the /etc/init.d/riak-cs script, however, when starting the process it reports ulimit is 1024.

Any clue?

**Comment by hectcastro** [comment]
@kandalf Can you shoot me your app.configs via e-mail?

**Comment by kandalf** [comment]
@hectcastro Sent! Thanks!

**Comment by kandalf** [comment]
Just for future reference, I was able to configure the testing node and create the initial user using this guide:
http://docs.basho.com/riakcs/latest/tutorials/fast-track/Building-a-Local-Test-Environment/

Pointed by @hectcastro 

Thanks!

**Comment by parmenides** [comment]
@kandalf  @hectcastro  Could you please send your Riak, Riak CS, and Stanchion app.config to payam.yousefii@gmail.com i have got the same problem.
