### ISSUE TITLE
refactor: remove throwing errors at bucket policy checking code [JIRA: RCS-342]

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#530]
#523 reminded us to refactor

**Comment by slfritchie** [comment]
Issue #523 has been closed -- is this issue still relevant?  Or can this be closed?

**Comment by kuenishi** [comment]
Yes and no, relevant. But can't be closed.

https://github.com/basho/riak_cs/blob/develop/src/riak_cs_s3_policy.erl#L594

This function `pairs_to_statement/2` returns raw value or throws error, instead of `{ok, _} {error, _}` tuple - to be fixed.

**Comment by shino** [comment]
Repo cleanup sweeping.
It seems this PR is stale. I will close it but please feel free to re-open.
