### ISSUE TITLE
Full support for PUT object - copy

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#548]
- Support object copying within Riak CS
- Add S3 API support. Docs are [here](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html)
- Add OpenStack API support. Docs are [here](http://docs.openstack.org/api/openstack-object-storage/1.0/content/copy-object.html#d6e1009)

**Comment by reiddraper** [comment]
@andrewjstone what's the latest status on this? Can it be ready for inclusion in 1.5 around March-ish?

**Comment by kellymclaughlin** [comment]
The main outstanding TODO is connecting up the webmachine resources iirc.

**Comment by shino** [comment]
Addressed by #868, will be released in 1.5.0 :sparkles:
