### ISSUE TITLE
405 Method Not Allowed on batch delete using boto

### ISSUE THREAD

**Issue by sglebs** [basho/riak_cs#549]
riak-cs barfs when S3_Bucket.delete_keys(keys) is used from boto: boto.exception.S3ResponseError: S3ResponseError: 405 Method Not Allowed

One needs to manually traverse the keys collection and issue individual delete commands, as in the old days of Amazon S3. Is there any hope of having this kind of support in riak-cs anytime soon?

stack trace:

  File "/Users/mqm/zzz/lib/python2.7/site-packages/boto/s3/bucket.py", line 566, in delete_keys
    while delete_keys2(headers):
  File "/Users/mqm/zzz/lib/python2.7/site-packages/boto/s3/bucket.py", line 565, in delete_keys2
    body)
boto.exception.S3ResponseError: S3ResponseError: 405 Method Not Allowed

**Comment by sglebs** [comment]
from boto.s3.connection import S3Connection, OrdinaryCallingFormat
import os

S3_PROXY_HOST = "riak1.foo.com" #riak
#S3_PROXY_HOST = None #amazon
#
S3_PROXY_PORT = "8091" #riak
#S3_PROXY_PORT = None #amazon
#
S3_ACCESS_KEY = "rrrrrrrrrrrrrr" #riak
#S3_ACCESS_KEY = "aaaaaaaaaaaaa" #amazon
#
S3_SECRET_KEY = "rrrrrrrrrrrrrrrrr" #riak
#S3_SECRET_KEY = "aaaaaaaaaaaaaaaaaaaaaa" #amazon
#
S3_HOST = host = "riak1.foo.com" #riak
#S3_HOST = host = "s3.amazonaws.com" #amazon
#
S3_BATCH_DELETE = True # use True to see riak's lack of support for a batch delete
#
S3_BUCKET = "sanitytest"
#
S3_Connector = S3Connection(S3_ACCESS_KEY, S3_SECRET_KEY, is_secure=False, host=S3_HOST, proxy=S3_PROXY_HOST, proxy_port=S3_PROXY_PORT, calling_format=OrdinaryCallingFormat(), debug = 2)
S3_Bucket = S3_Connector.create_bucket(S3_BUCKET)
print (S3_Bucket)
key = S3_Bucket.new_key("test_messenger/prune_mobile/foo/111/1")
key.set_contents_from_string({"age": 42}, reduced_redundancy=True)
keys = S3_Bucket.list ("test_messenger")
if S3_BATCH_DELETE:
    S3_Bucket.delete_keys(keys)
else:
    for key in keys:
        key.delete()
print (S3_Bucket)
S3_Connector.delete_bucket(S3_Bucket)

**Comment by kellymclaughlin** [comment]
We don't yet have support for the [`Delete Multiple Objects`](http://docs.aws.amazon.com/AmazonS3/latest/API/multiobjectdeleteapi.html) operation. 

Here's a link to our docs page showing what API operations are currently supported: http://docs.basho.com/riakcs/latest/references/apis/storage/
