### ISSUE TITLE
fs2 backend stability [JIRA: RCS-166]

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#555]
General goal: get the fs2 backend into a stable & usable state.  Bonus points for highest possible performance, but that will probably require talking directly to `prim_file` and so is probably best left as a separate work item.

**Comment by shino** [comment]
Close. Next step :)

**Comment by Basho-JIRA** [comment]
Ummm, this GH issue was closed on March 30, 2015. Closing in JIRA. 

**_[posted via JIRA by Scott Fritchie]**_
