### ISSUE TITLE
Get FSM `waiting_chunks` crash with `notfound`

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#567]
On "develop":

```
17:19:03.579 [error] CRASH REPORT Process <0.5241.0> with 0 neighbours
```

exited with reason:
{{{badmatch,{error,notfound}},[{riak_cs_get_fsm,waiting_chunks,2,[{file,"src/riak_cs_get_fsm.erl"},{line,270}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,494}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,227}]}]},{gen_fsm,sync_send_event,[<0.5310.0>,get_next_chunk,infinity]}}
in gen_fsm:sync_send_event/3 line 214

**Comment by shino** [comment]
Won't fix.

@slfritchie if you have any idea to fix this, please reopen.
