### ISSUE TITLE
Cannot update Content-Type

### ISSUE THREAD

**Issue by Schnouki** [basho/riak_cs#571]
I've been trying to update the `Content-Type` of an object stored in Riak CS using something similar to [this Gist](https://gist.github.com/garnaat/1791086). But `Content-Type` isn't updated.

You can also test this by adding `Content-Type` to the `ObjectMetadataTest` class of `client_tests/python/boto_test.py`.

**Comment by kellymclaughlin** [comment]
Can you tell me what version you are using or what branch if you are building from source?

**Comment by Schnouki** [comment]
I'm using version 1.3.1 on Debian (64bits).

**Comment by kellymclaughlin** [comment]
I suspect you are hitting the bug that was addressed in [this](https://github.com/basho/riak_cs/pull/563) PR. It has been merged to our `develop` branch and will be fixed in our next release.

**Comment by slfritchie** [comment]
@Schnouki Have you had a chance to review Kelly's comment?
