### ISSUE TITLE
riak_cs_gc:handle_mark_as_pending_delete() crash on timeout [JIRA: RCS-340]

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#602]
Sorry, I don't recall which git commit this happened with.  Probably 'develop' branch back on/near June 06.

```
2013-06-05 13:44:04.209 [error] <0.277.0> Supervisor
```

riak_cs_get_fsm_sup had child undefined started with
{riak_cs_get_fsm,start_link,undefined} at <0.12432.11> exit with
reason {{function_clause,[{riak_cs_gc,handle_mark_as_pending_delete,[{error,timeout},<<"slftest3">>,<<"15777">>,[],<0.182.0>],[{file,"src/riak_cs_gc.erl"},{line,174}]},{riak_cs_utils,get_manifests,3,[{file,"src/riak_cs_utils.erl"},{line,469}]},{riak_cs_manifest_fsm,handle_get_manifests,1,[{file,"src/riak_cs_manifest_fsm.erl"},{line,265}]},{riak_cs_manifest_fsm,waiting_command,3,[{file,"src/riak_cs_manifest_fsm.erl"},{line,201}]},{gen_fsm,handle_msg,7,[{file,"gen_fsm.erl"},{line,494}]},{proc_lib,init_p_do_apply,...}]},...}
in context child_terminated

**Comment by shino** [comment]
Fixed by #656.
