### ISSUE TITLE
Add syslog support

### ISSUE THREAD

**Issue by ksauzz** [basho/riak_cs#603]
One of users wants Riak CS syslog output to get logs aggregated

**Comment by kellymclaughlin** [comment]
This should be pretty simple to do. We can add [lager_syslog](https://github.com/basho/lager_syslog) as a dependency and it will just be a matter of configuration. 

What the level of urgency for this?

**Comment by ksauzz** [comment]
It is not urgent. It would be good if included in 1.4.

**Comment by argv0** [comment]
https://github.com/basho/riak_cs/pull/617

**Comment by ksauzz** [comment]
thanks!
