### ISSUE TITLE
Expose a way to calculate total storage amount used by the system [JIRA: RCS-339]

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#612]

**Comment by cmeiklejohn** [comment]
From looking at the requirements of the related basho/riak_cs_control#39 issue, it seems like it also needs a way to estimate a breakdown of usage by user, return the top users, space remaining, and take into account storage space used by items in Riak, metadata, stats, and the like.

**Comment by shino** [comment]
Just for information.
#723 also requires riak's cluster-wide disk usage information ( "cluster-wide minimum" of each node's free percentage" ). I guess it needs additional feature in riak side.

**Comment by shino** [comment]
Memo: Detailed storage stats #1120 is partial solution for this. it's not a raw disk usage in total but something that are invisible for users or normal storage stats does not show, such as lingering `writing` or `(pending|scheduled)_delete` volume estimate.

**Comment by kuenishi** [comment]
I think this is fine to close. If all Key-Value amount is known then it can calculated by our usual overhead calculators.
