### ISSUE TITLE
riakc_pb_socket usage: avoid reuse after timeout [JIRA: RCS-338]

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#613]
After a `timeout` using the `riakc_pb_socket` API, the client-side PID is invalid, so trying to use that PID again is invalid.

Suggestion: have the pooling API have a "replace" option where a PID checked out of a pool can be replaced with a (hopefully) better one, without worrying about the deadlock/high latency of trying to check out another PID from the same pool?

**Comment by shino** [comment]
Now, riak_cs connection pool of riakc_pb_socket uses `auto_reconnect` option. It's not an ideal fix for this issue... But I will close this issue because I think new issue/PR is better place to discuss.
