### ISSUE TITLE
Support https on the public riakcs.net deployment

### ISSUE THREAD

**Issue by diwakergupta** [basho/riak_cs#630]
The current S3-compatible endpoint for riakcs.net is http://data.riakcs.net:8080. For any kind of real production usage, we need a secure endpoint. I tried https://data.riakcs.net and https://data.riakcs.net:8080 and they obviously don't work. I additionally tried https://data.riakcs.net:8443 and that _does_ work but I couldn't find references to it anywhere so not sure if that's a supported/advertised endpoint.

**Comment by kellymclaughlin** [comment]
Agreed that this should be supported, but we do not directly control that service. We'll pass it on to the service maintainers though.
