### ISSUE TITLE
Unable to delete a user

### ISSUE THREAD

**Issue by jeffutter** [basho/riak_cs#652]
I have been trying to delete a user and it does not seem to work as expected.

I am attempting like this:

```
s3curl.pl --debug --id default --delete -- -x localhost:8080 http://riak-cs.s3.amazonaws.com/user/PBZL3QQVS4VS2MAYJKLT
```

I get an error like this

```
<?xml version="1.0" encoding="UTF-8"?><Error><Code>MethodNotAllowed</Code><Message>The specified method is not allowed against this resource.</Message><Resource>/riak-cs/user/PBZL3QQVS4VS2MAYJKLT</Resource><RequestId>12345</RequestId></Error>
```

Perhaps I am doing something wrong?

**Comment by kuenishi** [comment]
Currently Riak CS does not have capability of deleting an user account. We recommend just disabling the user - if you want to create a new user with same name, 1) change the name old one 2) disable it 3) create a new one with the same name.
