### ISSUE TITLE
Docs: add kernel tuning advice from #616

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#660]
Issues #616 has some hard-learned advice for kernel tuning parameters for CS in general and Linux in particular.  IMO this should be added to the CS docs.

**Comment by shino** [comment]
memo: http://linux.die.net/man/2/listen

> If the backlog argument is greater than the value in /proc/sys/net/core/somaxconn, then it is silently truncated to that value; the default value in this file is 128.

**Comment by michellep-basho** [comment]
Assigning this to 1.5.0. Please move it to 1.5.1 if there's not time to address it.

**Comment by kellymclaughlin** [comment]
I opened a PR to document the connection pools [here](https://github.com/basho/basho_docs/pull/1218) in which I referenced Andrew's digging on the RST packet rate limiting.

**Comment by kuenishi** [comment]
Great.
