### ISSUE TITLE
Performance of DELETE does not scale

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#681]
[IIJ presented a benchmark (mosly in Japanese, sorry)](http://www.slideshare.net/takashisogabe/riak-19684891) on Riak CS - the result was mostly good except scalability of DELETE. Probably this is due to PUT contention onto a single key in GC bucket when deleting an object.

The fix for this problem might be adding a suffix to a key in GC bucket like `<epoch>++<somerandomstuff>` . If we choose this fix list_keys in gc_d must be changed to stream_list_keys before.

note: this also addresses #6134

**Comment by reiddraper** [comment]
> This fix for this problem might be adding a suffix to a key in GC bucket like <epoch>++<somerandomstuff> . If we choose this fix list_keys in gc_d must be changed to stream_list_keys before.

This is definitely worth trying. Either way, I'd love to see the streaming list keys stuff added to the gc daemon.

**Comment by reiddraper** [comment]
Anyone know if we've seen the same performance bottlenecks with PUTs that overwrite a key? That should hit the same, synchrounous GC bucket writing code path as DELETE.

**Comment by shino** [comment]
Got some numbers for random prefix

code is here: https://github.com/basho/riak_cs/compare/release%2F1.4...feature%2Fgc-key-scattering
- 4 boxes, one riak + one riak-cs in each box
- basho_bench in another (5th) box, cs driver
- delete operation with preload 10KB objects
- compare release/1.4 branch and the branch above

```
| branch            | concurrent | DELs/sec |
|-------------------+------------+----------+
| release/1.4       |          1 |       50 |
| release/1.4       |          2 |       80 |
| release/1.4       |          4 |      100 |
| release/1.4       |          8 |      100 |
|-------------------+------------+----------+
| gc-key-scattering |          1 |       50 |
| gc-key-scattering |          8 |      220 |
| gc-key-scattering |         16 |      270 |
| gc-key-scattering |         32 |      300 |
```

The release/1.4 branch does not go beyond 100 DELs/sec, and
there happens 9 siblings at concurrent=4 and 36 siblings at concurrent=8.

By prepending random numbers, siblings is at most 2 with concurrent=8 or 16.
I don't understand why there is ~300 DELS/sec limit. User/Bucket get hot keys?

**Comment by reiddraper** [comment]
Nice work, thanks @shino!

**Comment by shino** [comment]
I have almost same throughput result for millisec suffix as random suffix.
The number of siblings `node_get_fsm_siblings_100` is different;
almost 1 for random suffix, but around 4 or 5 for millisec suffix.

Code of millisec suffix:

```
-spec generate_key(boolean()) -> binary().
generate_key(AddLeewayP) ->
    {MegaSec, Sec, MicroSec} = os:timestamp(),
    list_to_binary(
      integer_to_list(
         (MegaSec * 1000000 + Sec) * 1000 + MicroSec div 1000 +
            if not AddLeewayP -> 0;
               true           -> leeway_seconds() * 1000
            end)).
```

**Comment by reiddraper** [comment]
I don't have a particular preference between the two.

**Comment by shino** [comment]
Resolved by adding random numbers as key suffix at #689

**Comment by reiddraper** [comment]
#689 is merged, closing.
