### ISSUE TITLE
Three GETs to moss.buckets in PUT Object

### ISSUE THREAD

**Issue by shino** [basho/riak_cs#701]
There are three GETs to riak for bucket `moss.buckets`.

redbug trace at `release/1.4` branch is here 
https://gist.github.com/shino/584df113fd19c3139436
Lines starting `**` are my comments.

In total, GET x 7 + PUT x 3 requests to riak.

(It's better to look into `develop` branch :P )

**Comment by kuenishi** [comment]
addressed by #761
