### ISSUE TITLE
Add tests for access and storage statistics

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_cs#703]
We've had a couple of regressions recently -- paste due time to add some tests.

**Comment by shino** [comment]
Some tests for access stats are added at #747

**Comment by shino** [comment]
storage tests : https://github.com/basho/riak_cs/pull/800/files#diff-1

**Comment by kuenishi** [comment]
I thought this was meant to be some eqc testing for more safety.

**Comment by shino** [comment]
EQC over riak_test? Possible (reasonably) ?

**Comment by shino** [comment]
reopen for the place of discussion

**Comment by kuenishi** [comment]
+1 to close this and eqc testing might be future work or we totally update from scratch.
