### ISSUE TITLE
Riak-CS-GC timestamp for scheduler is in the year 0043, not 2013. 

### ISSUE THREAD

**Issue by th-m-vogel** [basho/riak_cs#713]
OS: Debian 7
RiakCS Version: 1.4.1, 1.4.2 (binary release) and  riak-cs_1.4.2.2.g6f8bcc0-1_amd64.deb build from src

RiakVersion: 4.2.2 binary release for Debian

> riak-cs-gc status
> There is no garbage collection in progress
>   The current garbage collection interval is: 900
>   Last run started at: undefined
>   Next run scheduled for: 00431021T082857Z

**Comment by kuenishi** [comment]
This is fixed at https://github.com/basho/riak_cs/pull/676 , but not included in 1.4 releases. Will be included in next 1.5 release.
