### ISSUE TITLE
Add concurrency to GC

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#716]
Currently the cleanup of deleted or overwritten object versions is done by the singleton GC daemon process. The daemon gathers the set of deletion-eligible keys from the GC bucket and iterates over the keys in a serial manner. Make changes so that the GC daemon starts and manages multiple worker processes. Also provide a way to dynamically add and remove worker processes during a GC run. The goal is to add more concurrency and control to the GC process in order to allow GC to better handle cases where there is large amount of cleanup work to do.

**Comment by reiddraper** [comment]
Remind me, is there work on a branch for this? If not, I say we push it to 1.6.

**Comment by kellymclaughlin** [comment]
Yeah it's [here](https://github.com/basho/riak_cs/tree/feature/gc-concurrency), though it is in need of rebase from current `develop`.

**Comment by shino** [comment]
@kellymclaughlin How about the status of the branch? Almost finished or need some more work?
I want this functionality in multi-cluster because it's possible that more garbage are generated.

I can take over the branch if you don't mind :)

**Comment by kellymclaughlin** [comment]
@shino Current status is the code should be working, but the `riak_cs_gc_d_eqc` test needs to be updated since it's currently not working. A similar test for the new gc worker module also needs to be added. If you want to pick it up that would be great.

**Comment by shino** [comment]
Thanks for the information.
The branch just rebased to current develop is [here](https://github.com/basho/riak_cs/tree/feature/gc-concurrency-rebased).

**Comment by shino** [comment]
Addressed by #830
