### ISSUE TITLE
HTTP uploads using POST

### ISSUE THREAD

**Issue by michellep-basho** [basho/riak_cs#735]
customer request

<b>drivers:</b> simplify use, S3 parity
<b>reference:</b> http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html

**Comment by reiddraper** [comment]
Dupe, or related to #182.

**Comment by michellep-basho** [comment]
oops, just realized that. will close.

**Comment by reiddraper** [comment]
my mistake too, dupe of #162, not 182.
