### ISSUE TITLE
block_get_retry statistic is incorrectly incremented? [JIRA: RCS-331]

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#750]
... by this line in the `ProceedFun`:

https://github.com/basho/riak_cs/blob/ee26ee2e12f00af0a9ea0cc1163523778914e53f/src/riak_cs_block_server.erl#L256

It's still a bit early in the morning on a Monday, but I'm wondering if an audit of all of the counter incrementing in this module would be worthwhile.

**Comment by shino** [comment]
Stats are re-new'ed in 2.1. Close.
