### ISSUE TITLE
CS docs do not mention 'connection_pools' attributes

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#752]
The Riak CS docs at docs.basho.com do not mention the `connection_pools` attributes of `request_pool` and `bucket_list_pool`.  This oversight should be fixed, together with some basic tuning advice.

**Comment by kellymclaughlin** [comment]
PR to address this: https://github.com/basho/basho_docs/pull/1218

**Comment by kuenishi** [comment]
Great.
