### ISSUE TITLE
Multiple "legend" attributes within statistics JSON output [JIRA: RCS-171]

### ISSUE THREAD

**Issue by hectcastro** [basho/riak_cs#764]
The Riak CS statistics JSON output contains multiple attributes for `legend`:

``` bash
$ riak-cs version
1.4.2
$ ./s3curl.pl --id admin --contentType application/json -- -s --proxy1.0 localhost:8080 http://s3.amazonaws.com/riak-cs/stats | jsonpp | grep "legend"
  "legend": [
  "legend": [
%
```

**Comment by kuenishi** [comment]
this came up again: zd://10621

**Comment by kuenishi** [comment]
More generally, the result of stats is very hard to grep.

**Comment by kuenishi** [comment]
We removed "legend" in CS 2.1.0. It's all flat JSON now.

**Comment by Basho-JIRA** [comment]
No release note needed. Maybe fixed via RCS-11 ? 

**_[posted via JIRA by Kota Uenishi]**_
