### ISSUE TITLE
Update riak compatibility matrix documentation

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_cs#767]
As seen [here](http://docs.basho.com/riakcs/latest/cookbooks/Version-Compatibility/#Working-Version-Combinations).

**Comment by kuenishi** [comment]
latest 1.4.5 combination added here: https://github.com/basho/basho_docs/tree/cs767-version-compatibility
Will add 1.5.0 later when it gets close.

**Comment by reiddraper** [comment]
@kuenishi do you want to go ahead and make a pull-request with that branch?

**Comment by kuenishi** [comment]
@reiddraper Yes, after 1.5.0 at Riak CS tagged. We should express version combination both on CS 1.4.x and 1.5.x . I'll add the following combination to that branch and make pull request:

```
(Riak, Riak CS, Stanchion) = (1.4.8, 1.5.0, 1.5.0)
```
