### ISSUE TITLE
One GET from riak-cs-gc and two GETs of manifest in single S3 PUT: necessity or waste?

### ISSUE THREAD

**Issue by shino** [basho/riak_cs#773]
https://github.com/basho/riak_cs/pull/761#issuecomment-32008837

**Comment by shino** [comment]
More detailed information needed. ping @kuenishi

**Comment by kuenishi** [comment]
here: https://gist.github.com/kuenishi/8348263

The second block shows there are two manifest gets after fetching moss_bucket_v1 record and before putting blocks.

**Comment by shino** [comment]
memo: riak_cs_get_fsm and riak_cs_put_fsm separately call get manifests.

**Comment by kuenishi** [comment]
After learning sibling explosion, this is a designed behaviour.
