### ISSUE TITLE
Querying storage statistics returns wrong JSON

### ISSUE THREAD

**Issue by antony66** [basho/riak_cs#797]
Hello there

[Riak CS documentation says](http://docs.basho.com/riakcs/latest/cookbooks/Querying-Storage-Statistics/) clearly that JSON response to storage access request should contain list of user's buckets and storage usage information about each of them i.e.

```
      "foo": {
        "Objects": 1,
        "Bytes": 32505856
      },
      "bar": {
        "Objects": 4,
        "Bytes": 130023424
      }
```

We're testing Riak CS 1.4.4 installed on Debian Wheezy x64 nodes from Debian package provided on the [official download page](http://docs.basho.com/riakcs/latest/riakcs-downloads/) and in our case resulting JSON looks as follows:

```
"struct":{"Objects":943,"Bytes":2868597},
"struct":{"Objects":307,"Bytes":752095},
"struct":{"Objects":351,"Bytes":3346306},
"struct":{"Objects":1158,"Bytes":19926176},
"struct":{"Objects":1327,"Bytes":629402195}},
```

It contains repeating word "struct" instead of bucket's names, while other information (number of files in a bucket and summary size in bytes) is correct.

I also noticed that if I request result in xml: 

```
s3cmd get s3://riak-cs/usage/<User-Key>/bx/20140205T160000Z/20140206T170000Z --force --no-progress - 
```

I get error 500 every time. This only applies to "b" (storage statistics type query), but not "a" type queries. Should I open another issue for this?

**Comment by ksauzz** [comment]
Thank you for the report.  I reproduced this issue. We will handle that!!

**Comment by kuenishi** [comment]
Closing as #800 merged.
