### ISSUE TITLE
List objects FSM v2 has poor performance with prefix requests.

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_cs#802]
The list objects v2 FSM does not use the `prefix` field in the request to skip past the lesser (lexicographically) set of results. I haven't dug in too much, but it may also not stop once a key has been seen that is _greater_ than the prefix. It should. [The code for constructing the start key](https://github.com/basho/riak_cs/blob/develop/src/riak_cs_list_objects_fsm_v2.erl#L366-L385) should take the prefix into account.

**Comment by reiddraper** [comment]
@shino Any thoughts on how to test this with the EQC test? The bug was _not_ a correctness issue, but a performance/efficiency one.

**Comment by kuenishi** [comment]
Closing as #804 merged. Nice catch.
