### ISSUE TITLE
Unresponsive Poolboy [JIRA: RCS-330]

### ISSUE THREAD

**Issue by zschlag** [basho/riak_cs#822]
It is possible for Poolboy to get into an unresponsive state where the output of  `[{Name, poolboy:status(Name)} || Name <- [request_pool, bucket_list_pool]].` never changes and therefore the pools can never drain.  Restarting Riak CS resolves the issue, but root causality is still unknown.

**Comment by shino** [comment]
I will close this issue in the course of repo issue cleanup because
it is inactive for long and not reproducible. Please feel free to reopen if necessary.
