### ISSUE TITLE
Decide on OTP version for Riak CS 1.5

### ISSUE THREAD

**Issue by reiddraper** [basho/riak_cs#847]
We've been building with R16, but we need to see what the ramifications of having the map/reduce code be built with R16 and run under a < Riak 2.0 which runs Erlang R15.

**Comment by kuenishi** [comment]
To make sure MapReduce stuff around usage and access calculation we should use same OTP version as Riak to avoid confusion. And we are about to test against 1.4.8, so R15 will be the choice.

I'll make sure combination in docs at #767 . The CS shipped after Riak 2.0 shipped may be with R16 (maybe 1.5.1 or later), which will be also mentioned at the doc.

**Comment by reiddraper** [comment]
I'll try and build develop with R15B03 again today.

**Comment by reiddraper** [comment]
Built fine with R1B01 (I didn't try B03). Should we switch the builders to use R15 too? I guess so.

**Comment by shino** [comment]
> Should we switch the builders to use R15 too? I guess so.

Sounds nice :+1:

**Comment by seancribbs** [comment]
Testers are now on R15, package builders were already on R15.

**Comment by reiddraper** [comment]
woot!

**Comment by shino** [comment]
Thanks @seancribbs & @reiddraper :exclamation:

**Comment by kuenishi** [comment]
Unfortunately creating plt files in R15 is very slow, which caused 1200sec timeout in bors test of dialyzer in #869 . http://buildbot.bos1/builders/test-riak_cs/builds/189

Is it realistic to run dialyzer in R16 and tests in R15, or, extend the timeout (to how many minutes)?

**Comment by seancribbs** [comment]
@kuenishi I manually built the top-level PLT on that builder yesterday, the dialyzer step should no longer timeout.

**Comment by kuenishi** [comment]
@seancribbs Cool. Thanks.
