### ISSUE TITLE
Storage calculation doesn't handle tombstones, nor handle undefined manifest.props

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#849]
around here: https://github.com/basho/riak_cs/blob/d0501f50a499ca0b1a4d5e55e850ff30d62ce129/src/riak_cs_storage.erl#L104

This leads to storage calculation skips the objects where `.props`  is  `undefined`.

**Comment by kuenishi** [comment]
Maybe related to #840 .

**Comment by shino** [comment]
just a note: object list (v1) properly uses upgrading:
https://github.com/basho/riak_cs/blob/release/1.4/src/riak_cs_utils.erl#L510

see also : #670 #671

**Comment by kuenishi** [comment]
see also: #524

**Comment by kuenishi** [comment]
#840 identified with this issue. will open another PR.
