### ISSUE TITLE
Change default value of `gc_paginated_indexes`

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#881]
Should it be in 1.5.0, or not?

**Comment by reiddraper** [comment]
I think I'm +1 on having this default change. As long as the Riak cluster is 1.4+, it should be OK. @kellymclaughlin?

**Comment by kellymclaughlin** [comment]
Yep agreed. As long as we stipulate in the docs that Riak >= 1.4 should be used then it should be fine.

**Comment by shino** [comment]
Addressed by #884. Close.
