### ISSUE TITLE
Overwritten keys remain active [JIRA: RCS-354]

### ISSUE THREAD

**Issue by shino** [basho/riak_cs#913]
`release/1.5` branch, commit 1b3b733e670524d2396a17858650c27a1d458b3e

Two PUTs to the same key produce two active manifests.

list manifests by inspector after two PUTs:

```
Key ============================: Sibl. == State ========== UUID =========================== Content-Length== First Block ====
rebar.config                    : 1        active           35dde9761bed44a19b0b539f558d4dff             2612 Found
rebar.config                    : 1        active           98bbd03426e540bea5c9ff54814525a8             2612 Found
```

Overwritten but active manifests can not be pruned by leeway or count (#732),
may result in large objects.

**Comment by reiddraper** [comment]
This is a known issue, and I _thought_ there was an issue filed about it. I haven't found it yet, but I'll keep looking. I seem to remember there was a reason this was non-trivial to solve.

**Comment by reiddraper** [comment]
One of the reasons we didn't address this sooner as well was that I was under the impression that this bug/mis-feature would only allow _two_ active manifests. Which, aside from the extra storage space of the actual object, should not contribute much to manifest bloat. Thoughts?

**Comment by shino** [comment]
Confirmed only two `active`s with many `scheduled_delete`s.

> should not contribute much to manifest bloat. Thoughts?

Completely Agree :smile: 

note: this can be closed if duplicated issue is found.

**Comment by shino** [comment]
Changed from 1.5.1 to 1.6.0 (because of low priority)

**Comment by reiddraper** [comment]
Great.

**Comment by kuenishi** [comment]
This is not reproducible in 2.1.1

```
a                                1        scheduled_delete 54e77fbd660949efb3c2b9ca01954bfc         41943040 multipart Found           
a                                1        active           6f16a081cd954e309a68aeaef25a249a         41943040 multipart Found  
```
