### ISSUE TITLE
riak_test against Riak 1.4.10

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#914]
In some tests, building cluster with joins fails with `{error, different_ring_sizes}` while all related Riak nodes have same ring sizes '8'. [Release notes](https://github.com/basho/riak/blob/1.4/RELEASE-NOTES.md#riak-1410-release-notes) didn't help me but will dig more.

**Comment by kuenishi** [comment]
The second attempt succeeded after downloading tarball source package. Still wondering why but close so far.

**Comment by shino** [comment]
All CS riak_test succeeded with riak_ee 1.4.10 (build by `git clone` and `make devrel`).
