### ISSUE TITLE
Review bucket restrictions and limitations

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#927]
"Each AWS account can own up to 100 buckets at a time."
 And make sure other limitations to protect the system.
http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

**Comment by shino** [comment]
It may be nice to make the limit as configuration item like `unlimited | non_neg_integer()`.

**Comment by kuenishi** [comment]
Other restrictions seems to be only in bucket names. So bucket number limitation is the only missing.
