### ISSUE TITLE
Multipart upload disappears after completing the other multipart [JIRA: RCS-270]

### ISSUE THREAD

**Issue by kuenishi** [basho/riak_cs#955]
Looks like completing multipart deletes other unrelated multipart uploads with different uploadId. Investigating a little bit more will let me find the root cause.

https://gist.github.com/kuenishi/e5a30fd75869cc537788

**Comment by shino** [comment]
Not reproduced. https://gist.github.com/shino/03d29a0a123fef979458
- riak_cs just before 2.1.0 (ad76f9c)
- s3cmd was build from git at `b99d589`

**Comment by kuenishi** [comment]
Oh dear, why (? ?). Do we have any test for this?

**Comment by kuenishi** [comment]
A year ago we only had 1.5, so I think this was for 1.5. Derp.

**Comment by shino** [comment]
I want one more person to confirm the result or reproduction. One possibility  is s3cmd version dependence. I think unlikely but for sure, what if it aborts all initiated uploads for the same key :bomb: (IIRC, old version of s3cmd deleted unfinished MP uploads when some error happened when uploading or it was killed by SIGTERM)

**Comment by kuenishi** [comment]
I'd like to close this just by writing some riak_test for this issue and by assuring it never happened.

**Comment by shino** [comment]
Not reproducible.
