### ISSUE TITLE
specifying admin user on fresh install produces error 500 (internal server error).

### ISSUE THREAD

**Issue by Pumpapa** [basho/riak_cs#970]
Fresh installed Riak 2.0.0 , Stanchion and Riak-cs 1.5.0 on a Fresh Netrunner (Debian Wheezy) VM without a hitch (all three pong). Following [Configuring Riak CS](http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-Riak-CS/) I am stuck at Specifying the Admin User.

```
curl -H 'Content-Type: application/json' -X POST --data '{"name":"admin", "email":"my@email.nl"}' http://127.0.0.1:8080/riak-cs/user
```

(and many variants) all produce 500: Internal Server Error

```
<html><head><title>500 Internal Server Error</title></head><body><h1>Internal Server Error</h1>The server encountered an error while processing this request</body></html>
```

I've read [this post](https://groups.google.com/forum/#!topic/nosql-databases/cYBR7E92Fho) and tried replacing cs_root_host with 127.0.0.1 without success

The error logs show: 
     2014-09-12 22:37:41.721 [error] <0.124.0> Lager event handler error_logger_lager_h exited with reason {'EXIT',{{badmatch,["/riak-cs/user",{error,{error,{badmatch,{error,malformed_xml}},[{riak_cs_s3_response,xml_error_code,1,[{file,"src/riak_cs_s3_response.erl"},{line,310}]},{riak_cs_s3_response,error_response,1,[{file,"src/riak_cs_s3_response.erl"},{line,235}]},{riak_cs_wm_user,accept_json,2,[{file,"src/riak_cs_wm_user.erl"},{line,119}]},{webmachine_resource,resource_call,3,[{file,"src/webmachine_resource.erl"},{line,186}]},{webmachine_resource,do,3,[{file,"src/we

Following the docs I am currently stuck.

**Comment by Pumpapa** [comment]
Whoa.
I now followed the [fast-track](http://docs.basho.com/riakcs/latest/tutorials/fast-track/) and I guess either `default_bucket_props` or `storage_backend` did it, because now I do get some JSON back.

Feel free to close this issue; I leave it open because this is still an issue in the docs at [Configuring Riak CS](http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-Riak-CS/)

Thanks

**Comment by kuenishi** [comment]
I guess you missed [Configuring Stanchion](http://docs.basho.com/riakcs/latest/cookbooks/configuration/Configuring-Stanchion/) section? Stanchion is another sub-package and process that is part of Riak CS cluster. Yes, the error messages are always confusing and misleading.

**Comment by Pumpapa** [comment]
I'm quite sure I did configure and start Stanchion. The link you sent concerns 1.5.1, a currently 'unreleased version of Riak', and I have only 1.5.0. Might that be a difference?
As said, using the fast track I am now further ahead, so if you feel the docs are ok it certainly is ok with me. Thanks.
