### ISSUE TITLE
I run the same command,but have diffient HTTP result  [JIRA: RCS-168]

### ISSUE THREAD

**Issue by ghost** [basho/riak_cs#971]
/root/s3curl/s3curl.pl --id=admin --head http://p-riakcs.9.91.18.38.xip.io/cloudfoundry-packages/12/01/120186da-f434-4c73-b926-b4d68f33d63f
HTTP/1.1 200 OK
Connection: close
Content-Length: 2190
Content-Type: application/zip
Date: Tue, 16 Sep 2014 12:28:24 GMT
Etag: "3ee22f6fdd3311abe920cd3db23f8a46"
Last-Modified: Tue, 16 Sep 2014 01:37:08 GMT
Server: Riak CS

/root/s3curl/s3curl.pl --id=admin --head http://p-riakcs.9.91.18.38.xip.io/cloudfoundry-packages/12/01/120186da-f434-4c73-b926-b4d68f33d63f
HTTP/1.1 403 Forbidden
Connection: close
Content-Length: 277
Content-Type: application/xml
Date: Tue, 16 Sep 2014 12:28:30 GMT
Server: Riak CS

please help me thanks.

**Comment by shino** [comment]
Thanks for the report and sorry for long silence.

This 403 seems like performance issue at riak kv layer. If this is still an issue, would you please post it to riak-users mailing list and let's discuss there.
