### ISSUE TITLE
No response to rel/bin/riak-cs version

### ISSUE THREAD

**Issue by shalako** [basho/riak_cs#973]
The documentation says this can be accomplished by running command-line tools. 

http://docs.basho.com/riakcs/latest/cookbooks/command-line-tools/#riak-cs

```
Usage: riak-cs {start | stop | restart | reboot | ping | console | attach | attach-direct | ertspath | chkconfig | escript | version | getpid | top [-interval N] [-sort reductions|memory|msg_q] [-lines N] }
```

On the node, this returns a blank line. Only by trying all the commands in the riak-cs/rel/bin directory, did I find the riak-cs version in the html output of riak-cs-admin cluster-info.

![screen shot 2014-09-19 at 3 46 25 pm](https://cloud.githubusercontent.com/assets/156568/4343271/ba64d146-4052-11e4-9ef0-a1bf554643bf.png)

![screen shot 2014-09-19 at 3 46 34 pm](https://cloud.githubusercontent.com/assets/156568/4343275/cd5fdfc0-4052-11e4-956c-ea424c0d53be.png)

**Comment by shalako** [comment]
We have the same issues with riak and stanchion. 
https://github.com/basho/riak/issues/599

I'm guessing the issue is related.

**Comment by jaredmorrow** [comment]
These are all the same case, when built from source, the APP_VERSION setting is not set and will report a blank line.  

If you need to make your own packages from source you can call `make package` which will package it for the operating system.
