### ISSUE TITLE
some feedback, some questions

### ISSUE THREAD

**Issue by p1tz** [basho/riak_cs#975]
I have been a long-time user of mogilefs. I was looking for replacements, because of SPOF. I evaluated different stuff, and got stuck with riak-cs (1.4.3 - 1.5.0).

Before I could use it, I had to do an erlang crashcourse to get it to do what I wanted. 
My use case is basically:
- clean rest api (created or modified riak_cs_no_rewrite, can't remember); I think the s3/openstack apis are god-aweful, and I am still stuck with the xml responses that riak-cs generates, but I can use a much nicer REST-URL-set.
- I take care of uniqueness of buckets and ids myself. So I looked at removing stanchion, which is unfortunately not an easy task for me, being an erlang noob. So I installed it on every riak-cs node, otherwise I would still have a SPOF.
- I have no users, I have one riak-cs user which owns everything. I make no use of bucket acls. I created or patched riak_cs_passthru_auth which does nothing and uses the dev-key thing, which is still annoying imho.

I think riak-cs suits my needs perfectly, except for those things I mentioned. I like the erlangy guarantees it gives me, and it is awesome at that. 

My questions are:
- is there nice json api which I have somehow overlooked? or is there going to be any, which just supports the basic get/put/delete/list... things?
- is there a way to strip it down to barebones not doing stats/user accounting and stuff like that?
- how can I easily replace stanchion (and by replace I mean get rid of it)?
- deployment is, well, I created a config deb for each cluster, I would be nice, if I could point a fresh riak-cs installation at a cluster, join it, and it would get the config of the cluster (all nodes are the same, except for hostname, ip, ..).

I would love to contribute, but I would do more harm than good with my erlang :(

ps: keep up the good work!

**Comment by kuenishi** [comment]
An argument whether a component of the system should involve the system setup, operation and requirement. Stanchion actually stores no and handles only updating user records and bucket metadata. Thus unless they are not required to be always up, Stanchion can't be SPOF and just booting them up manually often make overall operation much simpler and easier. Even if Stanchion is offline, you'll be able to create/update/delete objects.
However, operating Stanchion makes Riak CS's operation more complicated, I agree. We have a plan of getting rid of it, by using Riak 2.0's strong consistency.

Both S3/OpenStack API is core feature of Riak CS, but I understand there are needs on much simpler API of just handling large objects. It's still under discussion at our team, but if you want your own clean API, there is a way to do that. Currently CS has pluggable API definition, where riak_cs_s3_rewrite and riak_cs_oos_rewrite translated. You can make (or even contribute) you API by writing own rewrite module and configure to `rewrite_module` in app.config. The rewrite module is a translator of external REST API to internal REST API, which can be a very simple noop translator. Unfortunately `auth_module` is not well maintained Riak CS inside, so it won't work but fixing it around `riak_cs_wm_common` would be a good start point.

Stats and user accounting can't be removed right now without changing code, but hacking around `log_handlers` in webmachine section of app.config would also a good point to start.

Thank you for trying Riak CS, I hope you success with it.

**Comment by p1tz** [comment]
thank you!
