### ISSUE TITLE
riak-cs-debug should have a flag to skip access logs

### ISSUE THREAD

**Issue by bsparrow435** [basho/riak_cs#990]
Currently, riak-cs-debug grabs all logs. This creates huge debugs because the access logs can often be very large. There should be a flag to skip access logs or even give a time window and only grab access logs from that time window.

**Comment by ksauzz** [comment]
Addressed by #1076 

In Riak CS 2.0.0 or later, you can use `--skip-accesslog` option to skip access logs, and also `--log-mtime <days>` to skip old logs, default 14 days.
